[doc]: Docu for detrainment
avaframe/AvaFrame pull request #1004
Opened 2024-07-11 15:12 UTC by PaulaSp3

2024-08-12 08:19 UTC, fso42 requested changes
Please also add information to the https://docs.avaframe.org/en/latest/com1DFAAlgorithm.html#take-entrainment-into-account page similar to the entrainment info. I.e. information about how to activate it and set the parameters

2024-08-12 10:27 UTC, PaulaSp3 commented
@fso42  Should I also add the detrainment computation to the algorithm graph: https://docs.avaframe.org/en/latest/com1DFAAlgorithm.html ?

2024-08-12 14:57 UTC, fso42 commented
> @fso42 Should I also add the detrainment computation to the algorithm graph: https://docs.avaframe.org/en/latest/com1DFAAlgorithm.html ?
> 
> And should I also add detrainment in the [Theory](https://docs.avaframe.org/en/latest/theoryCom1DFA.html), in the mass balance equations etc.?

Yes and yes. Also with a senctence like "Snow entrainment can be added to the simulation" to make clear it is an option and not computed by default

2024-08-14 06:24 UTC, fso42 approved these changes

2024-08-19 07:34 UTC, fso42 submitted a review, later dismissed

2024-08-20 14:24 UTC, fso42 approved these changes

2024-08-20 14:41 UTC, merged