Update glossary.rst [doc]
avaframe/AvaFrame pull request #1026
Opened 2024-09-17 08:29 UTC by fso42

Concentrating on the definition of angles and points related to paths

2024-11-12 15:15 UTC, Marc-BFW requested changes
additionally, I suggest:

- [x] - line 6: '[...] of introducing and consolidating an [...]'
- [x] - line 8f: '[...] and in particular the [...]' 
- [x] - line 10: Avalanche Atlas

(the other collapsed sections I have not reviewed)

2024-11-12 15:15 UTC, Marc-BFW commented on docs/glossary.rst
> +        The travel angle describes the general inclination between the :term:`origin point` and the current location of interest.
```suggestion
        The travel angle describes the inclination between the :term:`origin point` and the current location of interest. 
```

2024-11-12 15:15 UTC, Marc-BFW commented on docs/glossary.rst
>          transitions, e.g., ‘powder avalanche with flow component’.
```suggestion
        transitions, e.g. ‘powder avalanche with flow component’.
```

2024-11-12 15:15 UTC, Marc-BFW commented on docs/glossary.rst
> +        (or beta_10), i.e., the point where the slope angle of the :term:`thalweg`
```suggestion
        (or beta_10), i.e. the point where the slope angle of the :term:`thalweg`
```

2024-11-12 15:15 UTC, Marc-BFW commented on docs/glossary.rst
> +        Runout lengths is intricately linked to the :term:`alpha point`, utilizing the
```suggestion
        Runout lengths is intrinsically linked to the :term:`alpha point`, utilizing the
```

2024-11-12 15:15 UTC, Marc-BFW commented on docs/glossary.rst
> +        by the AAA and relys on the horizontal extent, vertical depth of the fracture, volumn and mass of the deposited snow as well as the
```suggestion
        by the AAA and relies on the horizontal extent, vertical depth of the fracture, volume and mass of the deposited snow as well as the
```

2024-11-12 15:15 UTC, Marc-BFW commented on docs/glossary.rst
> +        runout length of the avalanche event. Thereby the largest possible event along a :term:`thalweg` is classified with R5.
```suggestion
        runout length of the avalanche event. Therefore the largest possible event along a :term:`thalweg` is classified with R5.
```

2024-11-12 15:15 UTC, Marc-BFW commented on docs/glossary.rst
> +        within the terrain of a given avalanche path. This maximum potential avalanche event corresponds with the
```suggestion
        within the terrain of a given avalanche path. This maximum potential avalanche event corresponds to the 
```

2024-11-12 15:15 UTC, Marc-BFW commented on docs/glossary.rst
> +        (American Avalanche Association, 2016). Therefore Dmax is defined accordingly to the destructive size
```suggestion
        (American Avalanche Association, 2016). Therefore Dmax is defined according to the destructive size
```

2024-11-12 15:15 UTC, Marc-BFW commented on docs/glossary.rst
> +        (accoridng to the avalanche size classifications of the Canadian Avalanche Association and the European
```suggestion
        (see avalanche size classifications of the Canadian Avalanche Association and the European
```

2024-11-12 15:15 UTC, Marc-BFW commented on docs/glossary.rst
> +        The deposition point describes the point along the thalweg where an avalanche event starts to decelerates
```suggestion
        The deposition point describes the point along the thalweg where an avalanche event starts to decelerate
```

2024-11-18 10:04 UTC, leon-wagner commented on docs/glossary.rst
> +        The travel angle increases with decreasing avalanche :term:`size`.
?

2024-11-19 11:01 UTC, leon-wagner requested changes
General suggestions and comments on definitions.

2024-11-19 11:08 UTC, leon-wagner commented on docs/glossary.rst
>          Terrain may be classified according to the Avalanche Terrain Exposure
something like: "Terrain classification refers to the systematic categorization of different types of ground surfaces based on their physical/optical/... or other characteristics."

2024-11-29 09:55 UTC, fso42 commented on docs/glossary.rst
> +        #Todo: Is gliding not a form of movement? what is meant by "avalanche criterion"?
@jtfisch : please check

2024-11-29 14:50 UTC, jtfisch commented on docs/glossary.rst
> +        associated with warm flow. Mixed types of movement are often observed,
remove the warm flow comment - it does not fit. rest is correct (i.e. DFA is a form of movement within the transition zone according to Avi Atlas)

2024-11-29 14:52 UTC, PaulaSp3 commented on docs/glossary.rst
> +        associated with warm flow. Mixed types of movement are often observed,
```suggestion
        associated with warm flow. Mixed types of movement are often observed,
```

2024-11-29 14:57 UTC, jtfisch commented on docs/glossary.rst
> +        avalanche. Dense Flow Avalanches (DFA) flow along the ground and are
```suggestion
        avalanche. Dense Flow Avalanches (DFA) flow along the ground
```

2024-11-29 14:58 UTC, jtfisch commented on docs/glossary.rst
> +        associated with warm flow. Mixed types of movement are often observed,
```suggestion
. Mixed types of movement are often observed,
```

2024-11-29 15:17 UTC, jtfisch requested changes

2024-11-29 15:17 UTC, jtfisch commented on docs/glossary.rst
> +        associated with warm flow. Mixed types of movement are often observed,
```suggestion
. Mixed types of movement are often observed,
```

2024-11-29 15:17 UTC, jtfisch commented on docs/glossary.rst
> +        #Todo: Is gliding not a form of movement? what is meant by "avalanche criterion"?
@leon-wagner - please double check the Avalanche Atlas wording : 
![image](https://github.com/user-attachments/assets/99cbc61b-2e45-4535-9454-afc5fccd68b4)

2024-11-29 15:17 UTC, jtfisch commented on docs/glossary.rst
> +        #Todo: Is gliding not a form of movement? what is meant by "avalanche criterion"?
```suggestion

```

2024-11-29 15:17 UTC, jtfisch commented on docs/glossary.rst
> +        and the altitude difference between the :term:`origin point` and the :term:`runout point`.
```suggestion
        and the altitude difference between the :term:`origin point` and the :term:`runout point` along the :term:`thalweg`.
```

2024-11-29 15:17 UTC, jtfisch commented on docs/glossary.rst
> +        The travel angle increases with decreasing avalanche :term:`size`.
```suggestion
        The beta angle increases with decreasing avalanche :term:`size`.
```

2024-11-29 15:17 UTC, jtfisch commented on docs/glossary.rst
> +        see :term:`zone of deposition`
```suggestion
       The runout area is associated to a specific avalanche event and usually located in the :term:`zone of deposition`.
```

2024-11-29 15:17 UTC, jtfisch commented on docs/glossary.rst
> +        the avalanche event from the :term:`origin point` to the :term:`runout point`.
```suggestion
        the avalanche event from the point of release or :term:`origin point` to the :term:`runout point`.
```

2024-12-02 18:12 UTC, merged