[com4]: Add an output raster: sum of flux
avaframe/AvaFrame pull request #1048
Opened 2024-11-29 13:07 UTC by PaulaSp3

- fix some small bugs (for log file)
- adapt the documentation: possible output files
- add two new output rasters: routing flux summed up over all paths (routFluxSum) & deposited flux summed up over all paths (depFluxSum)

2024-11-29 13:07 UTC, pep8speaks commented
Hello @PaulaSp3! Thanks for opening this PR. 

* In the file [`avaframe/com4FlowPy/com4FlowPy.py`](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/com4FlowPy.py):

> [Line 497:38](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/com4FlowPy.py#L497): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 494:13](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/com4FlowPy.py#L494): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 493:13](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/com4FlowPy.py#L493): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 440:121](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/com4FlowPy.py#L440): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 323:121](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/com4FlowPy.py#L323): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

* In the file [`avaframe/com4FlowPy/flowClass.py`](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/flowClass.py):

> [Line 352:23](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/flowClass.py#L352): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 341:52](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/flowClass.py#L341): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 341:51](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/flowClass.py#L341): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 337:1](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/flowClass.py#L337): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`avaframe/com4FlowPy/flowCore.py`](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/flowCore.py):

> [Line 197:105](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/flowCore.py#L197): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 195:69](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/flowCore.py#L195): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 195:38](https://github.com/avaframe/AvaFrame/blob/c457d443126196fc829b7318c33f6f20e479f2cb/avaframe/com4FlowPy/flowCore.py#L195): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator



Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2024-12-03 08:41 UTC, fso42 requested changes

2024-12-03 08:41 UTC, fso42 commented on avaframe/com4FlowPy/com4FlowPy.py
> +    # modelParameters["infra"]  = cfgSetup["infra"]
```suggestion
    # modelParameters["infra"]  = cfgSetup["infra"] Test
```

2025-01-09 15:06 UTC, ahuber-bfw requested changes
* Thx for the docstrings :+1: 
* Results with new/old flux distribution version look similar enough :+1: 
* I'm not 100% sure how to interpret the `depFluxSum` output yet 
* looks fine apart from minor changes

2025-01-10 07:39 UTC, PaulaSp3 commented on avaframe/com4FlowPy/com4FlowPy.py
>      cellCounts = SPAM.mergeRaster(modelPaths["tempDir"], "res_count")
I think yes. We want the sum of the cell counts over the paths right? I change it.

2025-01-10 08:34 UTC, PaulaSp3 commented on avaframe/com4FlowPy/rasterIo.py
>  def output_raster(file, file_out, raster):
I changed the first point.
I can do the second point when there is time (I'll make a new issue..) :)

2025-01-10 08:50 UTC, PaulaSp3 commented on docs/moduleCom4FlowPy.rst
>  .. Note::
Eigentlich die komplette Note oder? Also zu cell_count und dass man die output files im ini-file auswählen kann ?

2025-01-10 12:12 UTC, PaulaSp3 commented on docs/moduleCom4FlowPy.rst
> +- ``depFluxSum``: deposited flux summed up over all paths
[-> new issue](https://github.com/avaframe/AvaFrame/issues/1063)

2025-01-10 12:53 UTC, PaulaSp3 commented on avaframe/com4FlowPy/flowCore.py
> +    routFluxSumArray = np.zeros_like(dem, dtype=np.float32)
[issue](https://github.com/avaframe/AvaFrame/issues/1062)

2025-01-10 13:04 UTC, PaulaSp3 commented on avaframe/com4FlowPy/flowCore.py
> +            routFluxSumArray[cell.rowindex, cell.colindex] += cell.flux
- When John Sykes asked about suggestions to figure out terrain traps we (with @jtfisch ) thought about a routFluxSum - layer. 
- Maybe also here we could think of computing the maximum flux of one path(startcell) per cell and take the sum of flux over all paths? 
- another point was then to check if flux conserved using the depFluxSum and routFluxSum per generation: 
![image](https://github.com/user-attachments/assets/bdf3230d-42ec-443e-a5e9-4d465d40bf57)

2025-01-13 08:34 UTC, PaulaSp3 commented on avaframe/com4FlowPy/flowCore.py
>      if varUmaxBool:
I've tried to implement a check in that [commit](https://github.com/avaframe/AvaFrame/pull/1048/commits/a7087b7a467902ffd4c3a9f338ec09c4cb8ad6e7).

2025-01-13 10:25 UTC, ahuber-bfw commented on avaframe/com4FlowPy/rasterIo.py
> +        directory to raster file to reference on, mostly DEM
path to raster file

2025-01-13 10:40 UTC, PaulaSp3 commented on avaframe/com4FlowPy/rasterIo.py
> +        directory to raster file to reference on, mostly DEM
Now, all 'directory' in docstrings are changed to 'path'

2025-01-13 15:44 UTC, ahuber-bfw commented on avaframe/com4FlowPy/flowCore.py
>      if varUmaxBool:
ok, I had a look at the changes and adapted the `checkInputParameterValues` function in `com4FlowPy.py` slightly:

- substituted np.all() with np.any()
- removed the check for the `varExp` raster - since we don't have any sensible upper limit yet and negative `exp` values are already handled inside `flowCore.py`

2025-01-13 15:47 UTC, ahuber-bfw commented on avaframe/com4FlowPy/flowCore.py
> +            routFluxSumArray[cell.rowindex, cell.colindex] += cell.flux
Ok, this is definitely sth. we should discuss, for now it's ok the way it is i guess.

2025-01-13 15:57 UTC, ahuber-bfw commented on avaframe/com4FlowPy/com4FlowPy.py
> +def checkInputParameterValues(modelParameters, modelPaths):
I slightly changed the function

- checks for the 3 global parameters (alpha, exp, max_z) should be ok
- checks for variable rasters (varAlpha, varUmax) should also be ok for now, because they only write log-messages and don't change anything else
- we can think about handling this better later (I added a bullet point to https://github.com/avaframe/AvaFrame/issues/1062)

2025-01-13 16:18 UTC, ahuber-bfw approved these changes
Looks ok from my side now! 
* apart from the flux-conservation the PR does not introduce any major changes to the code, but adds some useful improvements (documentation, docStrings, etc.)
* @PaulaSp3: maybe you can run some tests if the `checkInputParameterValues`  function behaves as expected - I only checked/tested this function with the global parameters (which works) - __but not with the variable input rasters!__

2025-01-14 09:10 UTC, fso42 approved these changes

2025-01-16 10:04 UTC, fso42 commented
Standardtests ok, apart from Kot, Hof

2025-01-16 10:10 UTC, merged