Com7Regional
avaframe/AvaFrame pull request #1053
Opened 2024-12-10 13:52 UTC by leon-wagner

2024-12-10 13:52 UTC, pep8speaks commented
Hello @leon-wagner! Thanks for opening this PR. 

* In the file [`avaframe/com7Regional/com7Regional.py`](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/com7Regional/com7Regional.py):

> [Line 83:77](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/com7Regional/com7Regional.py#L83): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file
> [Line 48:1](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/com7Regional/com7Regional.py#L48): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 37:1](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/com7Regional/com7Regional.py#L37): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 13:1](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/com7Regional/com7Regional.py#L13): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`avaframe/in4Region/splitInputs.py`](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/in4Region/splitInputs.py):

> [Line 136:77](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/in4Region/splitInputs.py#L136): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file
> [Line 38:1](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/in4Region/splitInputs.py#L38): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 13:1](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/in4Region/splitInputs.py#L13): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`avaframe/runCom7Regional.py`](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/runCom7Regional.py):

> [Line 82:1](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/runCom7Regional.py#L82): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 60:24](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/runCom7Regional.py#L60): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 44:5](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/runCom7Regional.py#L44): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 14:1](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/runCom7Regional.py#L14): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`avaframe/runScripts/runSplitInputs.py`](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/runScripts/runSplitInputs.py):

> [Line 76:1](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/runScripts/runSplitInputs.py#L76): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file
> [Line 69:1](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/runScripts/runSplitInputs.py#L69): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 10:1](https://github.com/avaframe/AvaFrame/blob/617915f953d0c3941e68815ec567c126492f4113/avaframe/runScripts/runSplitInputs.py#L10): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2025-01-03 13:33 UTC, fso42 requested changes

2025-01-03 13:33 UTC, fso42 commented on avaframe/com7Regional/com7Regional.py
> +def processAvaDirCom1Regional(cfgMain, cfgCom7, avalancheDir):
Is it wanted that avalanchDir is required?

2025-01-03 13:33 UTC, fso42 commented on avaframe/com7Regional/com7Regional.py
> +def findAvaDirs(Dir):
docstring with parameters

2025-01-03 13:33 UTC, fso42 commented on avaframe/com7Regional/com7Regional.py
> +    avaDirs = [avaDir for avaDir in pathlib.Path(Dir).iterdir() if avaDir.is_dir() and
Mh, maybe use glob instead? Might be more robust...

2025-01-03 13:33 UTC, fso42 commented on avaframe/com7Regional/com7Regional.py
> +def moveOrCopyPeakFiles(cfg, avalancheDir, avaDirs):
docstring

2025-01-03 13:33 UTC, fso42 commented on avaframe/com7Regional/com7Regional.py
> +        shutil.rmtree(str(allPeakFilesDir)) #remove it if it already exists
Mh, is this always wanted? Or should there be an option to keep old results?

2025-01-03 13:33 UTC, fso42 commented on avaframe/com7Regional/com7Regional.py
> +    fileOperation = moveOrCopyFile
What is this for? why not use moveOrCopyFile directly?

2025-01-03 13:33 UTC, fso42 commented on avaframe/com7Regional/com7Regional.py
> +    for avadir in avaDirs:
To make this easier to read: 
make a list of all files to move with glob (one for the peakfiles and one ro the timesteps)
Then work on that list and move or copy it

2025-01-03 13:33 UTC, fso42 commented on avaframe/com7Regional/com7Regional.py
> +    fileOperationKwargs = {'copy': copyPeakFiles}
also, why not just use the boolean as argument for the moveOrCopyFile?

2025-01-03 13:33 UTC, fso42 commented on avaframe/com7Regional/com7RegionalCfg.ini
> +# set to 'True' to gather all output peakFiles from the avaDirectories
This is an either or decision, why have 2 booleans for that? 
I suggest something along the line of: moveInsteadOfCopy = True or similar
Default is to copy...

2025-01-03 13:33 UTC, fso42 commented on avaframe/com7Regional/com7RegionalCfg.ini
> +# expected mesh size [m]
Mh if you need this for development purposes, fine, but I would not set a cellsize, but instead work on what's given.

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +from shapely.geometry import shape, Point, box, MultiPolygon
Point, box, multiploygon are not used, please remove

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +    inputDEM = next(inputDir.glob("*.asc"), None)
Please mark this with a TODO, we are currently starting to include tif files as well, the glob needs to reflect that

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +def readShapefile(src):
I think this should be moved to either in1Data or in2Trans -> shapeUtils.py or similar

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +def createFolderList(inputShp):
docstring

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +        for i, (properties, geometry) in enumerate(zip(properties, geometries)):
This for loop does not need to live within the with, right? So it could be moved forward

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +            if not properties.get('name', '').strip():
Would it make sense to set a generic name here right away?

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +def groupFoldersByName(folderList):
docstring

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +def splitAndMoveReleaseAreas(folderList, inputShp, outputDir):
docstring

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +        featuresByName = {}
From here on down: does not need to live within the with, right?

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +        for entry in folderList:
Why not use groupFolderByName function, seems really similar?

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +        for name, features in featuresByName.items():
This is hard to read, maybe make a subfunction?

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +def clipDEMByCentroidAndMove(folderList, inputDEM, outputDir, cfg):
docstring

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +            geometry = entry['geometries'][0] #first geometry in list
this is the same for all of them? is that correct? If so, why is it then within the next for loop instead of the loop for folderList?

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +        for properties in entry['properties']:
I don't understand this for loop. Properties is never used, the geometry is always the same, leading to a center/buffersize etc that is the same for all entry[properties]....

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +        # Prepare header for clipped DEM
Please add a TODO here, again for tif additions

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +def splitByScenarios(folderList, outputDir):
docstring

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputs.py
> +    for folder in folderList:
as discussed, this needs to be simplified / made easier to be read. Let me know if you need help with this

2025-01-03 13:33 UTC, fso42 commented on avaframe/in4Region/splitInputsCfg.ini
> +#if DEM shall be split
Does it make sense to not split the DEM? Is there a case where this is not wanted?

2025-01-07 10:53 UTC, leon-wagner commented on avaframe/com7Regional/com7Regional.py
> +def processAvaDirCom1Regional(cfgMain, cfgCom7, avalancheDir):
yes, this is needed because the avalancheDir is updated multiple throughout the regional run and this function then uses that info

2025-01-08 15:31 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +            if not properties.get('name', '').strip():
Ah so that we set a generic name first, and then later in the grouping step we rename them by the attribute?

2025-01-09 12:55 UTC, leon-wagner commented on avaframe/com7Regional/com7RegionalCfg.ini
> +# set to 'True' to gather all output peakFiles from the avaDirectories
I've now changed the two booleans to have copy as default and optionally to moveInsteadOfCopy. Still two booleans are best i think because you may not always want this operation to happen at all, so the first one just controls that

2025-01-13 13:43 UTC, leon-wagner commented on avaframe/com7Regional/com7Regional.py
> +        shutil.rmtree(str(allPeakFilesDir)) #remove it if it already exists
Mhm, i see what you mean. I think it's best to delete it to avoid any conflicts, and if results are wanted to be kept one should rename the directory..

2025-01-13 13:43 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +            geometry = entry['geometries'][0] #first geometry in list
DEM clipping has been reworked now.

2025-01-13 13:43 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +        for properties in entry['properties']:
DEM clipping has been reworked now.

2025-02-21 10:59 UTC, awirb requested changes
I didn't check the pytests and the docu, still TODO

2025-02-21 10:59 UTC, awirb commented on avaframe/in4Region/splitInputs.py
> +        rowEnd = min(nRows, int((yMax - (yOrigin + nRows * cellSize)) / cellSize) + nRows)
why not: rowStart = max(0, int((yMin - (yOrigin )) / cellSize) )
        rowEnd = min(nRows, int((yMax - (yOrigin )) / cellSize) ) ?

2025-02-21 10:59 UTC, awirb commented on avaframe/in4Region/splitInputs.py
> +        # Convert extent to grid indices (using top-left origin)
isn't it the llcenter as origin? so lower left?

2025-02-21 10:59 UTC, awirb commented on avaframe/in4Region/splitInputs.py
> +        # Update transformation matrix for clipped DEM
could you use in2Trans/rasterUtils.py transformFromASCHeader(header)?

2025-02-21 10:59 UTC, awirb commented on avaframe/in4Region/splitInputs.py
> +        yMinDEM = clippedHeader['yllcenter'] - (cellSize/2) + cellSize
why not just         xMinDEM = clippedHeader['xllcenter'] + (cellSize*0.5)?

2025-02-21 10:59 UTC, awirb commented on avaframe/in4Region/splitInputs.py
> +        yMaxDEM = clippedHeader['yllcenter'] + (clippedHeader['nrows'] * cellSize) - (cellSize/2) - cellSize
same here?

2025-02-21 10:59 UTC, awirb commented on avaframe/in4Region/splitInputs.py
> +        groupExtents[dirName] = (xMinDEM, xMaxDEM, yMinDEM, yMaxDEM)
does this overwrite what was stored in line 389? if you use this here why is it done in line 389?

2025-02-21 10:59 UTC, awirb commented on avaframe/in4Region/splitInputs.py
> +            continue
again this could already be available if you use getInputCom1DFA once to create inputSimFiles dict

2025-02-21 10:59 UTC, awirb commented on avaframe/in4Region/splitInputs.py
> +def checkFeatureIsolation(geometries, properties, bufferSize, groupName):
where is this needed or called?

2025-02-21 10:59 UTC, awirb commented on avaframe/in4Region/splitInputsCfg.ini
> +#the splitting length around each avalanche scenario [m]
consider adding from what poin this buffer is added/subtracted

2025-02-21 16:51 UTC, awirb requested changes

2025-02-21 16:51 UTC, awirb commented on docs/moduleIn4Region.rst
> +    * Resistance areas (shapefile in RES directory)
consider adding where only one shp file is allowed

2025-02-21 16:51 UTC, awirb commented on docs/moduleIn4Region.rst
> +1. **Groups**: Collections of avalanche release areas that are located in the same spatial domain and may be wanted to be simulated together (e.g. divided into avalanche paths)
consider adding info on what is a release area, single feature in shp file?

2025-02-21 16:51 UTC, awirb commented on docs/moduleIn4Region.rst
> +Settings are controlled through ``splitInputsCfg.ini``, in which the ``bufferSize`` for the group bounding box is defined (which is used for DEM, RES, and ENT splitting).
is this buffer added/subtracted from the bounding box center? or from its corners?

2025-02-21 16:51 UTC, awirb commented on docs/moduleIn4Region.rst
> +2. Configure settings in ``in4RegionCfg.ini`` (or local version ``local_in4RegionCfg.ini``)
splitInputsCfg.ini instead of in4RegionCfg.ini?

2025-02-27 08:33 UTC, leon-wagner commented on docs/moduleIn4Region.rst
> +1. **Groups**: Collections of avalanche release areas that are located in the same spatial domain and may be wanted to be simulated together (e.g. divided into avalanche paths)
added

2025-02-27 08:57 UTC, leon-wagner commented on docs/moduleIn4Region.rst
> +2. Configure settings in ``in4RegionCfg.ini`` (or local version ``local_in4RegionCfg.ini``)
completely right, corrected

2025-02-27 09:38 UTC, leon-wagner commented on docs/moduleIn4Region.rst
> +Settings are controlled through ``splitInputsCfg.ini``, in which the ``bufferSize`` for the group bounding box is defined (which is used for DEM, RES, and ENT splitting).
added explanation

2025-02-27 09:45 UTC, leon-wagner commented on avaframe/runScripts/runSplitInputs.py
> +"""runScript for splitting avalanche input data into multiple folders based on individual release areas"""
added

2025-02-27 10:11 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +        rowEnd = min(nRows, int((yMax - (yOrigin + nRows * cellSize)) / cellSize) + nRows)
Took me a long time to figure this out, but basically I always had this issue that the DEM information was flipped and/or taking the wrong info from the larger input raster (which I think was related to the origin). 

Here it is explained by an AI:

In raster data (like DEMs):

The origin point (yOrigin) typically refers to the lower-left corner of the raster
The data array in Python is typically indexed from the top-left corner

Rows are counted from top to bottom in the array

The current code:

rowStart = max(0, int((yMin - (yOrigin + nRows * cellSize)) / cellSize) + nRows)
rowEnd = min(nRows, int((yMax - (yOrigin + nRows * cellSize)) / cellSize) + nRows)

accounts for this difference by:

1. Adding nRows * cellSize to transform from the lower-left origin to the top of the raster
2. Adding nRows at the end to flip the coordinate system

The suggested simpler version:

rowStart = max(0, int((yMin - yOrigin) / cellSize))
rowEnd = min(nRows, int((yMax - yOrigin) / cellSize))

would not work correctly because it doesn't account for the coordinate system transformation between:

- The geographic coordinate system (where y increases going north/up)
- The array index system (where row index increases going down)

This transformation is necessary because:

1. The DEM coordinates are in geographic space (measured from bottom-left)
2. But we need array indices (measured from top-left) to slice the data array

2025-02-27 10:15 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +        # Convert extent to grid indices (using top-left origin)
It might be that I have just ended up adding an extra step, where i flip the data for top-left origin once before clipping, then flip it again later when writing the raster.. It works but can probably be simplified

2025-02-27 10:21 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +        yMinDEM = clippedHeader['yllcenter'] - (cellSize/2) + cellSize
changed

2025-02-27 10:21 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +        yMaxDEM = clippedHeader['yllcenter'] + (clippedHeader['nrows'] * cellSize) - (cellSize/2) - cellSize
changed

2025-02-27 10:39 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +        groupExtents[dirName] = (xMinDEM, xMaxDEM, yMinDEM, yMaxDEM)
very good point, fixed it so that it is only stored in the end

2025-02-27 10:50 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +def checkFeatureIsolation(geometries, properties, bufferSize, groupName):
good point, this was intended for a check if features that were defined as a group were too isolated from each other to make sense to be defined as a group. essentially, an error should be raised in the case that the user defines groups that will cause unnecessarily large clipped DEMs, which would be counterproductive for the purpose of the script.

will look into where it can be called

2025-02-27 10:57 UTC, leon-wagner commented on avaframe/in4Region/splitInputsCfg.ini
> +#the splitting length around each avalanche scenario [m]
good point, added

2025-02-27 12:28 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +def checkFeatureIsolation(geometries, properties, bufferSize, groupName):
it works now as intended, after testing i realize its not the most fleshed out feature, but works as a simple feedback to the user in case of a simple isolated rel feature

2025-02-27 12:41 UTC, leon-wagner commented on avaframe/in4Region/splitInputs.py
> +    fields, fieldNames, properties, geometries, srs = readShapefile(inputShp)
good point, and would standardize it all a bit. remains as ToDo

although needs to be checked if our data format is compatible with shapely's functions which are used later for clipping

2025-09-02 13:12 UTC, fso42 approved these changes

2025-09-03 13:52 UTC, awirb requested changes
pytests and docu not yet reviewd

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/splitInputs.py
> +    on release area's "group" and "scenario" attributes provided in the release area file.
consider adding: If neither group nor scenario are provided, create one avalanche directory per release feature 

A question, what if scenarios are provided but no groups? as scenario names are not unique, it will just create one avaDir per release feature and scenarios won't have an effect right?
is there a check for this? if scenarios are provided but no groups?

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/splitInputs.py
> +        │   └── *.shp         # all release areas
if release features overlap, how is this handled?

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/splitInputs.py
> +        log.error(f"Expected 1 release area file, found {len(inputSimFilesAll['relFiles'])}.")
```suggestion
        log.error(f"Expected only one release area file, found {len(inputSimFilesAll['relFiles'])}.")
```

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/splitInputs.py
> +    outputDir.mkdir(parents=True, exist_ok=True)
consider using makeADir function of fileHandlerUtils

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/splitInputs.py
> +            targetDir.mkdir(parents=True, exist_ok=True)
makeADir function?

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/splitInputsCfg.ini
> +# The value for ``bufferSize`` is added to each direction (+x, -x, +y, -y) from a union bounding box with
consider adding 'from the borders or a union bounding box?

2025-09-03 13:52 UTC, awirb commented on avaframe/out3Plot/outCom7Regional.py
> +    yMax = yMin + cellSize * header["nrows"]
consider using plotUtils.py createExtentMinMax()

2025-09-03 13:52 UTC, awirb commented on avaframe/out3Plot/outCom7Regional.py
> +    yMax = yMin + cellSize * header["nrows"]
also includes a check for center and corner

2025-09-03 13:52 UTC, awirb commented on avaframe/runCom7Regional.py
> +        Path to the directory containing consolidated peak files, if enabled
I would avoid consolidated as it is just all the peak files from all the single avaDirs in one folder not like the merged ones, right? so maybe just' containing all the peak files from all the sub avaDirs'?

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/com7Regional.py
> +        Main configuration settings
avaframe?

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/com7Regional.py
> +    """Consolidate peak files from multiple avalanche directories.
collect/gather peak files from multiple avalanche directories into single directory

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/com7Regional.py
> +        dirPath.mkdir(parents=True, exist_ok=True)
consider using avaframe functions for this

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/com7Regional.py
> +    mergedData, outputTransform = merge(rasterFiles, method=mergeMethod, masked=True)
if the rasters have a different extent - does the rasterio merge function handle this?

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/com7Regional.py
> +    nRows = int((bounds["yMax"] - bounds["yMin"]) / outputTransform[0])
why not take the nrows and ncols of the mergedData directly?

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/com7RegionalCfg.ini
> +# faster version of com1DFA is used for the regional run (dt = 0.5 s), which however may lead to lower simulation accuracy.
where is this set? not here in the overrides

2025-09-03 13:52 UTC, awirb commented on avaframe/com7Regional/com7RegionalCfg.ini
> +# faster version of com1DFA is used for the regional run (dt = 0.5 s), which however may lead to lower simulation accuracy.
is this checked to give stable results with applied meshcellsize and sphkernelradius?

2025-09-03 15:17 UTC, fso42 commented on avaframe/com7Regional/com7Regional.py
> +    mergedData, outputTransform = merge(rasterFiles, method=mergeMethod, masked=True)
Yes, it could even handle different cellsizes...

2025-09-05 09:36 UTC, fso42 commented on avaframe/com7Regional/splitInputs.py
> +    on release area's "group" and "scenario" attributes provided in the release area file.
If no group is given, scenarios is ignored as well

2025-09-05 09:39 UTC, fso42 commented on avaframe/com7Regional/splitInputs.py
> +        │   └── *.shp         # all release areas
I'm not sure what you mean by this? If the features overlap, it does not matter for the splitting. It is being split according to group/scenario. If the overlapping features then end up in the same scenario shapefile, they are treated by com1DFA in the usual fashion...

2025-09-05 09:58 UTC, fso42 commented on avaframe/com7Regional/com7RegionalCfg.ini
> +# faster version of com1DFA is used for the regional run (dt = 0.5 s), which however may lead to lower simulation accuracy.
I will disable this completely, but during testing, this is still helpful :-)

2025-09-05 10:05 UTC, fso42 commented on avaframe/com7Regional/com7Regional.py
> +    nRows = int((bounds["yMax"] - bounds["yMin"]) / outputTransform[0])
This way an error is later thrown if the dimensions don't match... (dirty solution, I know). Added an explanation

2025-09-08 12:37 UTC, awirb commented on docs/moduleCom7Regional.rst
> +
maybe it would be interesting to note here why this is also required - that com1DFA shouldn't be driven with huge DEMs, even if the release scenarios are setup in a way that it is many scenarios that are run in parallel

2025-09-08 12:39 UTC, awirb commented on docs/moduleCom7Regional.rst
> +
and that therefore for a regional analysis that is often based on a single DEM?, this has to be first divided into several subregions in order to ensure an efficient computational workflow with com1DFA

2025-09-08 12:42 UTC, awirb commented on docs/moduleCom7Regional.rst
> +
and maybe also that it allows to provide result layers that aggregate individual scenarios or regions?

2025-09-08 12:44 UTC, awirb commented on docs/moduleCom7Regional.rst
> +* managing and aggregating outputs after a regional simulation, such as com1DFA peak files and merged rasters.
```suggestion
* managing and aggregating outputs after a regional simulation, e.q. merge com1DFA peak files to show maps of maximum, minimum or mean simulation results 
```

2025-09-08 12:50 UTC, awirb commented on docs/moduleCom7Regional.rst
> +
shall we add also here only one shp file is allowed?

2025-09-08 12:51 UTC, awirb commented on docs/moduleCom7Regional.rst
> +The module is intended to work with only one of each of these files. The first file that is found is the one that is used.
I still think adding the info directly is more helpful and also more consistent with what is written for the release shp file

2025-09-08 12:54 UTC, awirb commented on docs/moduleCom7Regional.rst
> +
shall we expand a bit on the concept of simulated together - so if multiple release features (plygons) in one shp file as input for com1DFA - these interact with each other (process interaction), however multiple scenarios in different shp files in one avalanche directory - no interaction -. but can be postprocessed to show max values of all scenarios for example (merged rasters)

2025-09-08 13:00 UTC, awirb commented on docs/moduleCom7Regional.rst
> +without much effort. Keep in mind however that this approach may result in a large amount of duplicated DEM data,
```suggestion
In the case that no attributes or values for ``group`` or ``scenario`` are provided, the procedure will create groups based on each release feature - so one avalanche directory, including a DEM and release scenario shp file, per release feature (polygon). This may be intended to simulate each release feature separately in an automated manner. However, keep in mind, that this approach may result in a large amount of duplicated DEM data,
```

2025-09-08 13:01 UTC, awirb commented on docs/moduleCom7Regional.rst
> +a larger value will ensure that no simulation will exit its domain, but with the drawback of producing larger output files.
and longer run times?

2025-09-08 13:03 UTC, awirb commented on docs/moduleCom7Regional.rst
> +2. Configure settings in ``splitInputsCfg.ini`` (or local version ``local_splitInputsCfg.ini``)
```suggestion
2. Copy ``splitInputsCfg.ini`` to a local version ``local_splitInputsCfg.ini`` and if desired adjust settings
```

2025-09-08 13:03 UTC, awirb commented on docs/moduleCom7Regional.rst
> +3. Either set path to avalanche directory in ``avaframeCfg.ini`` (or local version ``local_avaframeCfg.ini``) or
```suggestion
3. Either set path to avalanche directory in your local copy of ``avaframeCfg.ini`` ( ``local_avaframeCfg.ini``) or
```

2025-09-08 13:04 UTC, awirb commented on docs/moduleCom7Regional.rst
> +Running multiple avalanche dirs
as it is a heading, shall we call it avalanche directories? or to be consistent if this is required here avalancheDirs?

2025-09-08 13:05 UTC, awirb commented on docs/moduleCom7Regional.rst
> +A directory structure containing pre-configured avalanche directories (containing an ``Inputs`` folder) is required. For input preparation use
consider a reference to the inputs section of com1DFA

2025-09-08 13:07 UTC, awirb commented on docs/moduleCom7Regional.rst
> +After running com7 with the given module (e.g. :ref:`com1DFA <com1DFA>`), the standard output is located
are there currently other options?

2025-09-08 13:08 UTC, awirb commented on docs/moduleCom7Regional.rst
> +Additionally, com7 provides the option of aggregating all output peakFiles and tSteps results into a single directory
com7Regional

2025-09-08 13:10 UTC, awirb commented on docs/moduleCom7Regional.rst
> +Three configuration files are used (locals are preferred if they exist):
not true for com1DFACfg.ini unless in the com7REgionalCfg.ini setDefaultConfig=False in the com1DFA override section

2025-09-08 13:10 UTC, awirb commented on docs/moduleCom7Regional.rst
> +In essence, tasks are executed concurrently within each input avalanche directory, based on the number of currently available CPUs.
is it now sub_avalanche directories?

2025-09-08 13:11 UTC, awirb commented on docs/moduleCom7Regional.rst
> +3. Set path to avalanche directory in ``avaframeCfg.ini`` (or local version ``local_avaframeCfg.ini``)
same as above regarding local

2025-09-08 16:05 UTC, fso42 commented
Standardtests ok

2025-09-09 10:53 UTC, merged