[doc]: update (again) com4FlowPy docu
avaframe/AvaFrame pull request #1055
Opened 2024-12-16 16:20 UTC by PaulaSp3

from com4FlowPy installing part, delete all 'gdal' - descriptions (we don't need to install gdal seperatly).

2024-12-17 13:54 UTC, ahuber-bfw requested changes
Thx Paula,
I had a look at the current Installation instructions for Windows and suggested some minor changes.

2024-12-17 13:54 UTC, ahuber-bfw commented on docs/moduleCom4FlowPy.rst
> +If you have trouble installing ``rasterio`` on Windows use these links to
würde nach ein bisschen Recherche die Info hier für Windows reingeben ...

2024-12-17 13:54 UTC, ahuber-bfw commented on docs/moduleCom4FlowPy.rst
>  Running the Code
Additional installation requirements and running the code

2024-12-17 13:54 UTC, ahuber-bfw commented on docs/moduleCom4FlowPy.rst
> +Once the required libraries are installed the model runs via the ``runCom4FlowPy.py`` script, running:
Once the ``rasterio`` package is installed you can test :py:mod:`com4FlowPy` by:

1) setting ``avalancheDir = data/avaFlowPy`` inside ``local_avaframeCfg.ini`` in the ``avaframe`` directory (if you don't already hava a ``local_avaFrameCfg.ini`` create it by copying and renaming the ``avaframeCfg.ini`` -- also see next section below.)
2) running ``python runCom4FlowPy.py`` from within the ``avaframe`` directory.

2024-12-17 15:42 UTC, PaulaSp3 commented on docs/moduleCom4FlowPy.rst
> +- In order to run :py:mod:`com4FlowPy` you need to install ``rasterio`` separately, since they are not included in the general AvaFrame requirements (--> on Linux distributions inside the ``avaframe_
I tried to be a bit consistent with the general installation docu: 
![Screenshot from 2024-12-17 16-41-24](https://github.com/user-attachments/assets/111daecb-8161-43ec-b9ee-1eb22e67e738)

2024-12-18 07:59 UTC, ahuber-bfw approved these changes
thx, looks good now :)

2024-12-18 07:59 UTC, ahuber-bfw commented on docs/moduleCom4FlowPy.rst
> +Once the rasterio package is installed you can test :py:mod:`com4FlowPy`` by:
remove 1 extra ` behind `com4FlowPy`

2024-12-19 13:02 UTC, fso42 approved these changes

2024-12-19 13:02 UTC, merged