update check for extent of mu, xi fields
avaframe/AvaFrame pull request #1056
Opened 2024-12-19 10:19 UTC by awirb

2024-12-19 10:19 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py):

> [Line 2865:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L2865): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 120 characters)
> [Line 1323:59](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1323): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 1323:57](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1323): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 1323:51](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1323): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1136:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1136): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 1135:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1135): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 1135:86](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1135): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1135:56](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1135): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1134:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1134): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 1133:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1133): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 1133:86](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1133): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1133:56](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1133): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1126:56](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1126): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1125:40](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/com1DFA.py#L1125): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is None:'

* In the file [`avaframe/com1DFA/deriveParameterSet.py`](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/deriveParameterSet.py):

> [Line 743:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/deriveParameterSet.py#L743): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)
> [Line 334:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/deriveParameterSet.py#L334): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 334:85](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/deriveParameterSet.py#L334): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is not False:' or 'if cond:'
> [Line 286:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/deriveParameterSet.py#L286): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 120 characters)
> [Line 259:30](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/deriveParameterSet.py#L259): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 119:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/deriveParameterSet.py#L119): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 76:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/com1DFA/deriveParameterSet.py#L76): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)

* In the file [`avaframe/in1Data/getInput.py`](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py):

> [Line 901:52](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L901): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 896:52](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L896): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 813:36](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L813): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 812:36](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L812): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 520:45](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L520): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 507:18](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L507): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 463:46](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L463): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 460:33](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L460): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 450:43](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L450): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is None:'
> [Line 382:34](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L382): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 364:1](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L364): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 359:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb110a7b22eb84b/avaframe/in1Data/getInput.py#L359): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (136 > 120 characters)
> [Line 358:121](https://github.com/avaframe/AvaFrame/blob/62063e072aec59f50b5f65b46fb1 [...]

2024-12-23 15:43 UTC, fso42 requested changes

2024-12-23 15:43 UTC, fso42 commented on avaframe/com1DFA/com1DFACfg.ini
> +# resize files read from Inputs/RASTERS to be resized to extent of DEM as factor x meshCellSize
maybe write resizeThreshold x meshCellSize to make clear that this is the factor?

2024-12-23 15:43 UTC, fso42 commented on avaframe/com1DFA/deriveParameterSet.py
> +        cT = 0.
why cT and not rT?

2024-12-23 15:43 UTC, fso42 commented on avaframe/com1DFA/deriveParameterSet.py
> +    if diffX0 == 0 and diffY0 == 0 and diffY1 == 0 and diffX1 == 0 and inputField['header']['cellsize'] == demHeader['cellsize']:
Mh, we might have to use a threshold again, similar to meshCellSizeThreshold. We cannot guarantee that this always comes out to precisely 0...

Also you could use diffX0 == diffY0 == ... == 0 to shorten it a bit

2024-12-23 15:43 UTC, fso42 commented on avaframe/com1DFA/deriveParameterSet.py
> +    # compute difference of llcenter and urcenter - used for warning
Mh, this to line 59 could be a separate function, as I think this might be needed more often...

2025-01-10 08:26 UTC, awirb commented on avaframe/com1DFA/com1DFACfg.ini
> +# resize files read from Inputs/RASTERS to be resized to extent of DEM as factor x meshCellSize
added

2025-01-10 08:28 UTC, awirb commented on avaframe/com1DFA/deriveParameterSet.py
> +        cT = 0.
changed to rT

2025-01-10 08:32 UTC, awirb commented on avaframe/com1DFA/deriveParameterSet.py
> +    # compute difference of llcenter and urcenter - used for warning
do you mean until 849?

2025-01-10 08:49 UTC, fso42 commented on avaframe/com1DFA/deriveParameterSet.py
> +    if diffX0 == 0 and diffY0 == 0 and diffY1 == 0 and diffX1 == 0 and inputField['header']['cellsize'] == demHeader['cellsize']:
Mh, since this is purely a computational problem, I'd use similar tolerances to what we use elsewhere:
 ` np.isclose(simDF[key].values.reshape(-1, 1), value, atol=1.0e-7`

2025-01-10 08:52 UTC, fso42 commented on avaframe/com1DFA/deriveParameterSet.py
> +    # compute difference of llcenter and urcenter - used for warning
yes, sorry

2025-01-10 09:46 UTC, fso42 approved these changes

2025-01-10 12:12 UTC, fso42 commented
Standardtests ok, apart from know kot hof

2025-01-10 12:12 UTC, merged