Clean ainec visu
avaframe/AvaFrame pull request #118
Opened 2020-09-28 11:32 UTC by matthiasto

fix #115 
Cleaning the out3Aimec plots by creating a plot function
Updating the plots to use the new color map system
Sorting the input files properly before using them

2020-09-28 11:32 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/ana3AIMEC/ana3AIMEC.py`](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/ana3AIMEC/ana3AIMEC.py):

> [Line 725:21](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/ana3AIMEC/ana3AIMEC.py#L725): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 726:36](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/ana3AIMEC/ana3AIMEC.py#L726): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

* In the file [`avaframe/ana3AIMEC/dfa2Aimec.py`](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/ana3AIMEC/dfa2Aimec.py):

> [Line 18:1](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/ana3AIMEC/dfa2Aimec.py#L18): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 95:121](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/ana3AIMEC/dfa2Aimec.py#L95): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (138 > 120 characters)
> [Line 122:21](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/ana3AIMEC/dfa2Aimec.py#L122): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 122:57](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/ana3AIMEC/dfa2Aimec.py#L122): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'

* In the file [`avaframe/out3SimpPlot/makePalette.py`](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/makePalette.py):

> [Line 5:1](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/makePalette.py#L5): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 74:9](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/makePalette.py#L74): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 95:1](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/makePalette.py#L95): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 96:9](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/makePalette.py#L96): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 96:9](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/makePalette.py#L96): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 115:5](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/makePalette.py#L115): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

* In the file [`avaframe/out3SimpPlot/outAIMEC.py`](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py):

> [Line 77:24](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L77): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 89:39](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L89): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 92:25](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L92): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 141:5](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L141): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 220:11](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L220): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 221:14](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L221): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 222:14](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L222): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 223:14](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L223): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 237:24](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L237): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 240:28](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L240): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 307:39](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L307): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 339:13](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/outAIMEC.py#L339): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'

* In the file [`avaframe/out3SimpPlot/plotSettings.py`](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/plotSettings.py):

> [Line 20:72](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/plotSettings.py#L20): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 47:1](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/plotSettings.py#L47): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 88:110](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/plotSettings.py#L88): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 88:111](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/plotSettings.py#L88): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 88:121](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/plotSettings.py#L88): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 120 characters)
> [Line 89:6](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/plotSettings.py#L89): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 93:8](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/plotSettings.py#L93): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 94:6](https://github.com/avaframe/AvaFrame/blob/aea76682580fbd7513265e7d6c782553000b9048/avaframe/out3SimpPlot/plotSettings.py#L94): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 99:8](https://github.com/ava [...]

2020-09-28 20:35 UTC, fso42 requested changes
The logic of plotSettings.py needs to change.  

- We need an .ini file with the pure settings part. 

- There are quite some parameter like (figW, figH, lw, ms, fs etc) which should go to this ini file

- And a new .py file with takes the ini and does the setting logic for matplotlib (eg. plotUtils.py)
 -> can also contain those general function like the myNonUnifIM

The build is currently failing (build pytest) -> I added a note at the beginnig of plotSettings.py

I think we need to address these issues first, so I did not test the plots yet, and also did not look at the outAIMEC yet... 

Also be aware: once this is PR is merged, out1 and out3 are going to be renamed like discussed in our meeting (see Admin techDoc) -> out1Peak and out3Plot

2020-09-28 20:35 UTC, fso42 commented on avaframe/avaframeCfg.ini
> +continuousCmap = False
Please move this to Flags or move it to the plotting ini file ( I feel the second option is the better one)

2020-09-28 20:35 UTC, fso42 commented on avaframe/out3SimpPlot/plotSettings.py
This is not a good idea:
apart from it not working on a clean install (see the test build of this PR (pytest) ), 
it is dangerous to read a config twice-> what if the user decides to dynamically change a setting variable in his main script without being aware that a module reads it again...
-> we should keep this the way it is at the moment: the main script reads the cfg and supplies this to the modules...

2020-09-28 20:35 UTC, fso42 commented on avaframe/out3SimpPlot/plotSettings.py
>  matplotlib.rcParams["savefig.format"] = 'png'
Stuff like this should go to an ini file

2020-09-28 20:35 UTC, fso42 commented on avaframe/out3SimpPlot/plotSettings.py
> +    return ref, im
As mentioned in main comment -> extra .py file

2020-09-29 06:15 UTC, matthiasto commented
The plotting settings are now given in the plotUtils.ini in in3Utils. They are read by plotUtils.py still in in3Utils. The plotting environment is also set there.

2020-09-29 08:33 UTC, fso42 approved these changes

2020-09-29 09:23 UTC, merged