Add info on adding benchmark test
avaframe/AvaFrame pull request #233
Opened 2020-12-10 11:31 UTC by awirb

2020-12-10 17:22 UTC, pep8speaks commented
Hello @awirb! Thanks for updating this PR. 

* In the file [`avaframe/in2Trans/ascUtils.py`](https://github.com/avaframe/AvaFrame/blob/e3b7a829d67a1d67feac2dca57910063553130cb/avaframe/in2Trans/ascUtils.py):

> [Line 172:43](https://github.com/avaframe/AvaFrame/blob/e3b7a829d67a1d67feac2dca57910063553130cb/avaframe/in2Trans/ascUtils.py#L172): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 15:1](https://github.com/avaframe/AvaFrame/blob/e3b7a829d67a1d67feac2dca57910063553130cb/avaframe/in2Trans/ascUtils.py#L15): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2020-12-14 07:00 UTC, matthiasto approved these changes

2020-12-14 07:52 UTC, fso42 requested changes

2020-12-14 07:52 UTC, fso42 commented on docs/develop.rst
> +Now, you are ready to go! Just move to ``AvaFrame/avaframe`` and run: ::
```suggestion
Now, you are ready to go! Move to ``AvaFrame/avaframe`` and run: ::
```

2020-12-14 08:09 UTC, fso42 approved these changes

2020-12-14 08:12 UTC, merged