Update docu and reading of release area scenario
avaframe/AvaFrame pull request #260
Opened 2021-01-04 11:31 UTC by awirb

2021-01-04 11:31 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/in1Data/getInput.py`](https://github.com/avaframe/AvaFrame/blob/1c28e3d4f550c54f99662235b14bf3653d9f5903/avaframe/in1Data/getInput.py):

> [Line 69:37](https://github.com/avaframe/AvaFrame/blob/1c28e3d4f550c54f99662235b14bf3653d9f5903/avaframe/in1Data/getInput.py#L69): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 57:16](https://github.com/avaframe/AvaFrame/blob/1c28e3d4f550c54f99662235b14bf3653d9f5903/avaframe/in1Data/getInput.py#L57): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 53:5](https://github.com/avaframe/AvaFrame/blob/1c28e3d4f550c54f99662235b14bf3653d9f5903/avaframe/in1Data/getInput.py#L53): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-01-04 19:00 UTC, fso42 requested changes

2021-01-05 07:04 UTC, awirb commented on docs/moduleCom1DFA.rst
> +* releaseScenario - name of release area scenario shapfile (with or without extension -shp, if multiple, separate by '_')
due to the way makeSimDict works, the release area scenarios are not 'allowed' to have an underscore, this is also described in the docu

2021-01-05 07:11 UTC, awirb commented on docs/moduleOut3Plot.rst
> +statsPlots can be used produce scatter plots using a peak dictionary where information on two result parameters of avalanche simulations is saved.
Done but using is saved

2021-01-05 07:15 UTC, awirb commented on docs/moduleOut3Plot.rst
> +There is also the option to add a kde plot for each result paramter as marginal plots.
done

2021-01-05 07:27 UTC, awirb commented on docs/moduleCom1DFA.rst
> +* releaseScenario - name of release area scenario shapfile (with or without extension -shp, if multiple, separate by '_')
we could accept any name and  convert it to one not including any '_'

2021-01-05 07:46 UTC, fso42 approved these changes

2021-01-05 08:11 UTC, merged