Add option to export first and last time step of flow depth
avaframe/AvaFrame pull request #274
Opened 2021-01-14 10:32 UTC by awirb

* add plot function to plot single dataset and profile with profile axis and location to be specified in ini file 
* reset com1DFA deleteOutputFalse=False

2021-01-14 10:32 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/com1DFA/com1DFA.py):

> [Line 347:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/com1DFA/com1DFA.py#L347): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 346:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/com1DFA/com1DFA.py#L346): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 258:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/com1DFA/com1DFA.py#L258): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 120 characters)
> [Line 255:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/com1DFA/com1DFA.py#L255): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

* In the file [`avaframe/in3Utils/fileHandlerUtils.py`](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py):

> [Line 362:31](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L362): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 357:24](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L357): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 356:78](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L356): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 332:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L332): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 325:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L325): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 317:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L317): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 313:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L313): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 305:18](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L305): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 237:30](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L237): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 171:32](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L171): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 135:37](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L135): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 66:68](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L66): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 66:39](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L66): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 66:23](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/in3Utils/fileHandlerUtils.py#L66): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'

* In the file [`avaframe/out3Plot/outQuickPlot.py`](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/out3Plot/outQuickPlot.py):

> [Line 440:5](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/out3Plot/outQuickPlot.py#L440): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 356:1](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/out3Plot/outQuickPlot.py#L356): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 237:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/out3Plot/outQuickPlot.py#L237): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 120 characters)
> [Line 232:30](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/out3Plot/outQuickPlot.py#L232): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 178:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/out3Plot/outQuickPlot.py#L178): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 162:121](https://github.com/avaframe/AvaFrame/blob/306764d48b1e259d7c3e42edeb89e7a569108848/avaframe/out3Plot/outQuickPlot.py#L162): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)



Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-01-19 06:42 UTC, fso42 requested changes

2021-01-19 06:42 UTC, fso42 commented on avaframe/com1DFA/com1DFACfg.ini
> +# if True also flow depth of first and last time step are exported
```suggestion
# if True: flow depth of first and last time step are exported
```

2021-01-19 06:42 UTC, fso42 commented on avaframe/com1DFA/varyMu.cint
> +    set(Var, "ExportFieldRasterAscii", OutFile);
This whole block could go to the generate_report function, right? Since you repeat it 3 times, it's a lot of duplicated code...

2021-01-19 06:42 UTC, fso42 commented on avaframe/com1DFA/varyRelTh.cint
> +    set(Var, "ExportFieldRasterAscii", OutFile);
see comment varyMu.cint

2021-01-19 06:42 UTC, fso42 commented on avaframe/com1DFA/runStandardSimulation.cint
> +    set(Var, "ExportFieldRasterAscii", OutFile);
see comment varyMu.cint

2021-01-19 06:42 UTC, fso42 commented on avaframe/in3Utils/fileHandlerUtils.py
> +            if True also first and last time step of flow depth are exported
```suggestion
            if True: first and last time step of flow depth are exported
```

2021-01-19 06:42 UTC, fso42 commented on avaframe/in3Utils/fileHandlerUtils.py
> +            pathTo = os.path.join(outDirPF, 'timeSteps', '%s_%.05f_tLast_fd.asc' % (logDict['simName'][k], logDict[varPar][k]))
```suggestion
            pathTo = os.path.join(outDirPF, 'timeSteps', '%s_%.05f_tLast_fd.asc' 
                                              % (logDict['simName'][k], logDict[varPar][k]))
```

2021-01-19 06:42 UTC, fso42 commented on avaframe/in3Utils/fileHandlerUtils.py
> +            pathTo = os.path.join(outDirPF, 'timeSteps', '%s_%.05f_tFirst_fd.asc' % (logDict['simName'][k], logDict[varPar][k]))
```suggestion
            pathTo = os.path.join(outDirPF, 'timeSteps', '%s_%.05f_tFirst_fd.asc' 
                                               % (logDict['simName'][k], logDict[varPar][k]))
```

2021-01-19 06:42 UTC, fso42 commented on avaframe/out3Plot/outQuickPlot.py
> +    print('shape', ny, nx)
please remove

2021-01-19 08:38 UTC, awirb commented on avaframe/out3Plot/outQuickPlot.py
> +    print('shape', ny, nx)
Done

2021-01-19 10:48 UTC, fso42 approved these changes

2021-01-19 10:54 UTC, merged