Pretify dfa py
avaframe/AvaFrame pull request #276
Opened 2021-01-19 14:32 UTC by matthiasto

2021-01-19 14:32 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/com1DFAPy/SPHfunctions.py`](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/SPHfunctions.py):

> [Line 462:27](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/SPHfunctions.py#L462): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 238:27](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/SPHfunctions.py#L238): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','

* In the file [`avaframe/com1DFAPy/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/com1DFA.py):

> [Line 1246:24](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/com1DFA.py#L1246): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 568:5](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/com1DFA.py#L568): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 417:9](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/com1DFA.py#L417): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

* In the file [`avaframe/com1DFAPy/runCom1DFA.py`](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/runCom1DFA.py):

> [Line 217:86](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/runCom1DFA.py#L217): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 180:121](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/runCom1DFA.py#L180): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (145 > 120 characters)
> [Line 152:14](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/runCom1DFA.py#L152): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 84:1](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/runCom1DFA.py#L84): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment

* In the file [`avaframe/com1DFAPy/testSPH.py`](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py):

> [Line 365:121](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L365): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (144 > 120 characters)
> [Line 361:121](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L361): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (141 > 120 characters)
> [Line 361:119](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L361): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ','
> [Line 360:92](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L360): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ','
> [Line 359:92](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L359): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ','
> [Line 336:121](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L336): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (144 > 120 characters)
> [Line 332:121](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L332): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (141 > 120 characters)
> [Line 332:119](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L332): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ','
> [Line 331:92](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L331): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ','
> [Line 330:92](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L330): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ','
> [Line 258:26](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L258): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 217:9](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L217): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 201:29](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L201): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 201:28](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L201): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 179:71](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L179): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 79:18](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L79): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 79:17](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L79): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 67:121](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L67): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (131 > 120 characters)
> [Line 57:121](https://github.com/avaframe/AvaFrame/blob/0275a97436467b861c5018a1ff86e41a05304de0/avaframe/com1DFAPy/testSPH.py#L57): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 120 characters)



Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-01-20 18:48 UTC, fso42 commented
Computation of runCom1DFA.py fails if
`contCMap` in `plotUtilsCfg.ini  = False`
which is the default. 
Please make sure to not rely on the config if your data producing routine does not provide discrete data! -> set continous to True in com1DFA.py line 1487....

2021-01-20 19:07 UTC, fso42 requested changes
Following issues:

- Please see my comment outside of this review
- You adjusted the GeneralPlotHeader.tex, but did not provide the tex file to produce the new plot? (Fig 8 in docs)

2021-01-20 19:07 UTC, fso42 commented on docs/2_5DSPH.rst
> +
Please split this equation, it is getting too wide on the docs. 
![image](https://user-images.githubusercontent.com/6945681/105222302-9f233100-5b5a-11eb-85b5-4de1814a77a4.png)

Same goes for equations 9, 13 of the com1DFA Kernel theory

2021-01-21 07:35 UTC, awirb requested changes

2021-01-22 09:04 UTC, merged