Add option to save time steps of choice
avaframe/AvaFrame pull request #281
Opened 2021-01-22 14:30 UTC by awirb

2021-01-22 14:30 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/com1DFAPy/runCom1DFA.py`](https://github.com/avaframe/AvaFrame/blob/69d0c142572b5d3f281275033f0c1ed68d2a566a/avaframe/com1DFAPy/runCom1DFA.py):

> [Line 198:121](https://github.com/avaframe/AvaFrame/blob/69d0c142572b5d3f281275033f0c1ed68d2a566a/avaframe/com1DFAPy/runCom1DFA.py#L198): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 198:116](https://github.com/avaframe/AvaFrame/blob/69d0c142572b5d3f281275033f0c1ed68d2a566a/avaframe/com1DFAPy/runCom1DFA.py#L198): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 198:94](https://github.com/avaframe/AvaFrame/blob/69d0c142572b5d3f281275033f0c1ed68d2a566a/avaframe/com1DFAPy/runCom1DFA.py#L198): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 159:121](https://github.com/avaframe/AvaFrame/blob/69d0c142572b5d3f281275033f0c1ed68d2a566a/avaframe/com1DFAPy/runCom1DFA.py#L159): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (149 > 120 characters)

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-01-25 07:19 UTC, awirb commented on avaframe/com1DFAPy/com1DFACfg.ini
> +tSteps = 0|1|-1
yep for now yes, I could change it to be turned to an index using the dtSave though?

2021-01-25 07:36 UTC, matthiasto commented on avaframe/com1DFAPy/com1DFACfg.ini
> +tSteps = 0|1|-1
okok just pay attention that only the time steps saved can be printed, so this also depends on the dtSave you choose

2021-01-25 08:12 UTC, awirb commented on avaframe/com1DFAPy/com1DFACfg.ini
> +tSteps = 0|1|-1
done

2021-01-25 08:26 UTC, fso42 requested changes

2021-01-25 08:26 UTC, fso42 commented on avaframe/com1DFAPy/com1DFACfg.ini
> +# saving time step, will be converted to saving time step that comes before the one given and -1 can be used to export last time step
```suggestion
# saving time step, i.e.  time in seconds, will be converted to saving time step that comes before the one given and -1 can be used to export last time step 
```

Is this true?

2021-01-25 09:46 UTC, fso42 approved these changes

2021-01-25 10:51 UTC, awirb commented
I updated this to be more versatile as there is a function in in3Utils added to call the index of the time step and the 'real' time step appears in the peak file naming now

2021-01-25 15:13 UTC, fso42 approved these changes

2021-01-26 07:16 UTC, merged