3d plots for DEM's
avaframe/AvaFrame pull request #295
Opened 2021-02-03 21:59 UTC by fso42

- Adds new plotDEM3D function to plot any topography from an avalanche directory (ideal and real)
- new get and readDEM functions to provide an easy way to read DEMs
- rework some of the plotDEM functions
- updates configparser reading to keep capital cases in keys

**BEWARE**: generateTopoCfg changed **UPDATE YOUR local_ COPY**

fixes #292

2021-02-03 21:59 UTC, pep8speaks commented
Hello @fso42! Thanks for opening this PR. 

* In the file [`avaframe/ana3AIMEC/ana3AIMEC.py`](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/ana3AIMEC/ana3AIMEC.py):

> [Line 608:54](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/ana3AIMEC/ana3AIMEC.py#L608): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 323:129](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/ana3AIMEC/ana3AIMEC.py#L323): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 323:121](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/ana3AIMEC/ana3AIMEC.py#L323): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (187 > 120 characters)
> [Line 308:5](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/ana3AIMEC/ana3AIMEC.py#L308): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 71:121](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/ana3AIMEC/ana3AIMEC.py#L71): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 62:121](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/ana3AIMEC/ana3AIMEC.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)

* In the file [`avaframe/in1Data/getInput.py`](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in1Data/getInput.py):

> [Line 113:37](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in1Data/getInput.py#L113): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 101:16](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in1Data/getInput.py#L101): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 97:5](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in1Data/getInput.py#L97): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 19:1](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in1Data/getInput.py#L19): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`avaframe/in3Utils/cfgUtils.py`](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/cfgUtils.py):

> [Line 186:1](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/cfgUtils.py#L186): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 83:37](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/cfgUtils.py#L83): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator

* In the file [`avaframe/in3Utils/generateTopo.py`](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py):

> [Line 451:70](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L451): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 451:30](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L451): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 451:9](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L451): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 450:70](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L450): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 450:30](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L450): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 450:9](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L450): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 440:71](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L440): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 440:46](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L440): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 439:71](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L439): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 439:46](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L439): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 436:26](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L436): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 435:32](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L435): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 435:15](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L435): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 434:32](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L434): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 434:15](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L434): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 433:37](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L433): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 427:38](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L427): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 427:24](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L427): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 426:104](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L426): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 426:64](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L426): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 426:24](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.py#L426): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 425:104](https://github.com/avaframe/AvaFrame/blob/2c3f848712d16bd8bb047ca51b49978df29c33ff/avaframe/in3Utils/generateTopo.p [...]

2021-02-08 09:00 UTC, awirb requested changes
Maybe it would be good to add an example where the plotDEM3D is used? for example in runCom1DFA.py?

2021-02-09 18:40 UTC, fso42 commented on avaframe/out3Plot/outTopo.py
> +    plt.savefig(outName)
Done. This function now has an optional showPlot Flag...

2021-02-09 19:44 UTC, fso42 commented on avaframe/out3Plot/outTopo.py
> +    if cfgDEM.getboolean('showplot'):
Created an issue

2021-02-09 19:53 UTC, merged