Rename V to FV, global debugPlot, output plots saved
avaframe/AvaFrame pull request #307
Opened 2021-02-12 12:29 UTC by awirb

fix #304 , fix #300 , fix #301

2021-02-12 12:29 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/ana1Tests/damBreak.py`](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py):

> [Line 231:5](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L231): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 229:20](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L229): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 227:20](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L227): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 225:27](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L225): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 219:20](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L219): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 217:30](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L217): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 217:20](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L217): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 215:20](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L215): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 213:27](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L213): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 162:8](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L162): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 161:8](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L161): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 156:22](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L156): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 141:5](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L141): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 95:24](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L95): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 78:27](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L78): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 77:27](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L77): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 34:22](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L34): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:22](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 32:37](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L32): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\p'
> [Line 32:26](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/damBreak.py#L32): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\d'

* In the file [`avaframe/ana1Tests/simiSol.py`](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py):

> [Line 602:5](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L602): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 591:121](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L591): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 590:40](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L590): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 590:21](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L590): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 589:40](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L589): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 589:21](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L589): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 586:121](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L586): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 586:78](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L586): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 585:78](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L585): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 581:47](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L581): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 581:28](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L581): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 580:47](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L580): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 580:28](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L580): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 577:121](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L577): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 577:85](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L577): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 576:85](https://github.com/avaframe/AvaFrame/blob/014b2c7f1ddc0e4b3bb4a006b8a5bd6dd4700639/avaframe/ana1Tests/simiSol.py#L576): [E231](https://duckduckgo.com/?q=pep8%20 [...]

2021-02-15 07:40 UTC, matthiasto approved these changes

2021-02-15 07:52 UTC, matthiasto requested changes

2021-02-15 07:52 UTC, matthiasto commented on avaframe/com1DFAPy/runCom1DFA.py
> +        fU.makeADir(outDirPlots)
if several plot are made, there is a log "outdir plots" every time
...

2021-02-15 09:06 UTC, fso42 approved these changes

2021-02-15 11:21 UTC, merged