added DAM in parabola topo, renamed/cleaned topo naming
avaframe/AvaFrame pull request #335
Opened 2021-02-26 07:48 UTC by jtfisch

- watch out if the change in ToPo Name changes have consequences somewhere else.
- also created an issue that the parameters should be ordered according to topos

2021-02-26 07:48 UTC, pep8speaks commented
Hello @jtfisch! Thanks for opening this PR. 

* In the file [`avaframe/in3Utils/generateTopo.py`](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py):

> [Line 472:70](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L472): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 472:30](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L472): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 472:9](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L472): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 471:70](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L471): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 471:30](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L471): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 471:9](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L471): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 461:71](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L461): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 461:46](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L461): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 460:71](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L460): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 460:46](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L460): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 457:26](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L457): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 456:32](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L456): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 456:15](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L456): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 455:32](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L455): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 455:15](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L455): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 454:37](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L454): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 448:38](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L448): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 448:24](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L448): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 447:104](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L447): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 447:64](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L447): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 447:24](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L447): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 446:104](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L446): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 446:64](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L446): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 446:24](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L446): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 444:42](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L444): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 443:42](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L443): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 440:27](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L440): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 439:13](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L439): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 435:42](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L435): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 435:28](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L435): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 412:5](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L412): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 333:13](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L333): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 332:46](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L332): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 325:46](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L325): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 298:35](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L298): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ','
> [Line 298:26](https://github.com/avaframe/AvaFrame/blob/ada2b258a0a25c4c958d6eeddb1f2ca575f6af77/avaframe/in3Utils/generateTopo.py#L298): [E201](https:/ [...]

2021-02-26 10:33 UTC, fso42 requested changes

2021-02-26 10:33 UTC, fso42 commented on avaframe/in3Utils/generateTopo.py
> +        if cfg['TOPO'].getboolean('topoadd'):
Please stick to our naming convention, i.e.
```suggestion
        if cfg['TOPO'].getboolean('topoAdd'):
```

Maybe this is an opportunity to finally change all the ones that are in the Ini file, i.e c_extent to cExtent and so on...

2021-02-26 10:33 UTC, fso42 commented on avaframe/in3Utils/generateTopo.py
> +        #damPos = float(cfg['DAMS']['damPos'])
please delete

2021-02-26 10:33 UTC, fso42 commented on avaframe/in3Utils/generateTopo.py
> +        damheight = cfg['DAMS'].getfloat('damheight')
```suggestion
        damHeight = cfg['DAMS'].getfloat('damHeight')
```

2021-02-26 10:33 UTC, fso42 commented on avaframe/in3Utils/generateTopo.py
> +        damwidth = cfg['DAMS'].getfloat('damwidth')
```suggestion
        damWidth = cfg['DAMS'].getfloat('damWidth')
```

2021-02-26 10:33 UTC, fso42 commented on avaframe/in3Utils/generateTopoCfg.ini
> +damheight = 75
Naming convention, see above

2021-02-26 10:33 UTC, fso42 commented on avaframe/in3Utils/generateTopoCfg.ini
> +yl = 0.0
Should this be changed?

2021-02-26 10:45 UTC, fso42 commented
Oh, one thing I forgot: please adjust the test_generateTopo to account for your changes -> pytest fails at the moment...

2021-03-02 08:29 UTC, matthiasto approved these changes

2021-03-02 09:45 UTC, merged