Add plots aimec
avaframe/AvaFrame pull request #344
Opened 2021-03-04 10:11 UTC by matthiasto

Fixed entrainment bug in com1DFAPy (we were always using entrainment...)
Added comparison plot to AIMEC

2021-03-04 10:11 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/ana3AIMEC/ana3AIMEC.py`](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/ana3AIMEC.py):

> [Line 686:25](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/ana3AIMEC.py#L686): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 324:129](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/ana3AIMEC.py#L324): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 324:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/ana3AIMEC.py#L324): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (187 > 120 characters)
> [Line 309:5](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/ana3AIMEC.py#L309): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 71:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/ana3AIMEC.py#L71): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 62:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/ana3AIMEC.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)

* In the file [`avaframe/ana3AIMEC/dfa2Aimec.py`](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/dfa2Aimec.py):

> [Line 151:62](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/dfa2Aimec.py#L151): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 151:25](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/dfa2Aimec.py#L151): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 118:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/dfa2Aimec.py#L118): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 109:1](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/dfa2Aimec.py#L109): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 98:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/ana3AIMEC/dfa2Aimec.py#L98): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (138 > 120 characters)

* In the file [`avaframe/com1DFAPy/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py):

> [Line 1634:17](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L1634): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 1605:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L1605): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 120 characters)
> [Line 1605:120](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L1605): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1598:59](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L1598): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1597:138](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L1597): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1597:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L1597): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (152 > 120 characters)
> [Line 1590:83](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L1590): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1590:53](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L1590): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 934:5](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L934): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 862:26](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L862): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 850:9](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L850): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 663:9](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L663): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 114:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L114): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 92:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/com1DFAPy/com1DFA.py#L92): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (131 > 120 characters)

* In the file [`avaframe/in3Utils/fileHandlerUtils.py`](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/in3Utils/fileHandlerUtils.py):

> [Line 400:31](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/in3Utils/fileHandlerUtils.py#L400): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 395:24](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/in3Utils/fileHandlerUtils.py#L395): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 394:78](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/in3Utils/fileHandlerUtils.py#L394): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 370:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/in3Utils/fileHandlerUtils.py#L370): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 363:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/in3Utils/fileHandlerUtils.py#L363): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 355:48](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/in3Utils/fileHandlerUtils.py#L355): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 348:18](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/in3Utils/fileHandlerUtils.py#L348): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 331:121](https://github.com/avaframe/AvaFrame/blob/b821386cbc3a933d85d83d4101f562368fafec2b/avaframe/in3Utils/fileHandlerUtils.py#L331): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 327:22](https:/ [...]

2021-03-04 15:59 UTC, fso42 requested changes
Since there is a lot of overlap with PR #342 I only looked ad the outAIMEC.py. Once that PR is merged, rebase on the master and then I'll review it again if needed...

2021-03-04 15:59 UTC, fso42 commented on avaframe/out3Plot/outAIMEC.py
> +
I suggest making a small internal function that does the plotting and styling which you can call 3 time with the input
`XXCrossMaxAll, label, title`

2021-03-08 08:47 UTC, fso42 approved these changes

2021-03-10 12:15 UTC, matthiasto commented
replaced by branch refactorAimec #346

2021-03-10 12:15 UTC, closed without merging

2021-03-10 12:42 UTC, awirb reviewed
* suggestion: add a warning if aimec doesn't start to run, e.g. if no results from one computational module are available