Add option to filter benchs by avaName and update ini
avaframe/AvaFrame pull request #347
Opened 2021-03-05 14:20 UTC by awirb

2021-03-05 14:20 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/ana1Tests/testUtilities.py`](https://github.com/avaframe/AvaFrame/blob/4465c7f776fb0f7149887b7083ff0e5d92648430/avaframe/ana1Tests/testUtilities.py):

> [Line 114:22](https://github.com/avaframe/AvaFrame/blob/4465c7f776fb0f7149887b7083ff0e5d92648430/avaframe/ana1Tests/testUtilities.py#L114): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 113:18](https://github.com/avaframe/AvaFrame/blob/4465c7f776fb0f7149887b7083ff0e5d92648430/avaframe/ana1Tests/testUtilities.py#L113): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 113:18](https://github.com/avaframe/AvaFrame/blob/4465c7f776fb0f7149887b7083ff0e5d92648430/avaframe/ana1Tests/testUtilities.py#L113): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 37:35](https://github.com/avaframe/AvaFrame/blob/4465c7f776fb0f7149887b7083ff0e5d92648430/avaframe/ana1Tests/testUtilities.py#L37): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 25:17](https://github.com/avaframe/AvaFrame/blob/4465c7f776fb0f7149887b7083ff0e5d92648430/avaframe/ana1Tests/testUtilities.py#L25): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-03-08 06:40 UTC, matthiasto approved these changes

2021-03-08 08:53 UTC, fso42 requested changes

2021-03-08 08:53 UTC, fso42 commented on avaframe/ana4Stats/getStatsCfg.ini
> +Aimec = False
```suggestion
aimec = False
```

2021-03-08 08:53 UTC, fso42 commented on avaframe/com1DFA/com1DFA.py
> +            if cfgPar.getboolean('VarEnt') and (simName + '_entres_dfa') in cuSim:
```suggestion
            if cfgPar.getboolean('varEnt') and (simName + '_entres_dfa') in cuSim:
```

2021-03-08 08:53 UTC, fso42 commented on avaframe/com1DFA/com1DFACfg.ini
> +VarEnt = True
```suggestion
varEnt = True
```

2021-03-08 08:53 UTC, fso42 commented on avaframe/runStatsExample.py
> +    if cfg.getboolean('Aimec') == True:
```suggestion
    if cfg.getboolean('aimec') == True:
```

2021-03-08 08:53 UTC, fso42 commented on benchmarks/avaFlatPlaneVarParTest/avaFlatPlaneVarPar_com1DFACfg.ini
> +VarEnt = True
```suggestion
varEnt = True
```

2021-03-08 08:53 UTC, fso42 commented on benchmarks/avaHelixChannelVarParTest/avaHelixChannelVarPar_com1DFACfg.ini
> +VarEnt = True
```suggestion
varEnt = True
```

2021-03-08 08:53 UTC, fso42 commented on benchmarks/avaParabolaVarParTest/avaParabolaVarPar_com1DFACfg.ini
> +VarEnt = True
```suggestion
varEnt = True
```

2021-03-08 13:30 UTC, awirb commented on avaframe/ana4Stats/getStatsCfg.ini
> +Aimec = False
Done

2021-03-08 13:31 UTC, awirb commented on avaframe/com1DFA/com1DFA.py
> +            if cfgPar.getboolean('VarEnt') and (simName + '_entres_dfa') in cuSim:
Done

2021-03-08 13:31 UTC, awirb commented on avaframe/com1DFA/com1DFACfg.ini
> +VarEnt = True
Done

2021-03-08 13:31 UTC, awirb commented on avaframe/runStatsExample.py
> +    if cfg.getboolean('Aimec') == True:
Done

2021-03-08 13:46 UTC, awirb commented on benchmarks/avaFlatPlaneVarParTest/avaFlatPlaneVarPar_com1DFACfg.ini
> +VarEnt = True
Done

2021-03-08 13:47 UTC, awirb commented on benchmarks/avaHelixChannelVarParTest/avaHelixChannelVarPar_com1DFACfg.ini
> +VarEnt = True
done

2021-03-08 13:47 UTC, awirb commented on benchmarks/avaParabolaVarParTest/avaParabolaVarPar_com1DFACfg.ini
> +VarEnt = True
done

2021-03-08 14:51 UTC, fso42 approved these changes

2021-03-08 15:01 UTC, merged