Improve histogram plot
avaframe/AvaFrame pull request #378
Opened 2021-04-01 13:28 UTC by matthiasto

2021-04-01 13:28 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/out3Plot/outQuickPlot.py`](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py):

> [Line 521:5](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L521): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 438:1](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L438): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 316:121](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L316): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 120 characters)
> [Line 310:30](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L310): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 254:121](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L254): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 238:121](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L238): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 237:121](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L237): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 160:69](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L160): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 160:42](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L160): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 135:48](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L135): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 78:44](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L78): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 78:31](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/out3Plot/outQuickPlot.py#L78): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

* In the file [`avaframe/runComparisonTestsPy.py`](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py):

> [Line 161:121](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py#L161): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (163 > 120 characters)
> [Line 144:5](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py#L144): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 108:5](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py#L108): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 90:5](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py#L90): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 89:5](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py#L89): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 64:5](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py#L64): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 61:39](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py#L61): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 52:5](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py#L52): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 32:23](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py#L32): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 32:23](https://github.com/avaframe/AvaFrame/blob/e0fe7d6e863836f59d517c75349bae3c39127f34/avaframe/runComparisonTestsPy.py#L32): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-04-06 11:39 UTC, awirb requested changes

2021-04-06 13:41 UTC, matthiasto commented on avaframe/runComparisonTestsPy.py
> +    avaName = os.path.basename(avaDir)
not sure what you mean

2021-04-07 06:33 UTC, awirb commented on avaframe/runComparisonTestsPy.py
> +    avaName = os.path.basename(avaDir)
the parameter test that you define in line 47

2021-04-07 11:30 UTC, matthiasto commented
see new pR
Create plots diff #381

2021-04-07 11:30 UTC, closed without merging