Create plots diff
avaframe/AvaFrame pull request #381
Opened 2021-04-07 11:30 UTC by matthiasto

Improve histogram plot in the comparison plot
Add comparison routine

2021-04-07 11:30 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py):

> [Line 390:29](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L390): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 387:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L387): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 386:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L386): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (175 > 120 characters)
> [Line 381:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L381): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (167 > 120 characters)
> [Line 329:29](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L329): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 325:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L325): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (168 > 120 characters)
> [Line 311:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L311): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 311:90](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L311): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 302:17](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L302): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 276:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L276): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 120 characters)
> [Line 273:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L273): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 258:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L258): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (163 > 120 characters)
> [Line 246:13](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFA/com1DFA.py#L246): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented

* In the file [`avaframe/com1DFAPy/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py):

> [Line 1737:17](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L1737): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 1708:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L1708): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 120 characters)
> [Line 1708:120](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L1708): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1701:59](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L1701): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1700:138](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L1700): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1700:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L1700): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (152 > 120 characters)
> [Line 1693:83](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L1693): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1693:53](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L1693): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 1010:5](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L1010): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 716:9](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L716): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 458:39](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L458): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ':'
> [Line 117:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L117): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 120 characters)
> [Line 105:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/com1DFAPy/com1DFA.py#L105): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)

* In the file [`avaframe/in2Trans/ascUtils.py`](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/in2Trans/ascUtils.py):

> [Line 176:47](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/in2Trans/ascUtils.py#L176): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 174:51](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/in2Trans/ascUtils.py#L174): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 15:1](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/in2Trans/ascUtils.py#L15): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`avaframe/log2Report/generateCompareReport.py`](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/log2Report/generateCompareReport.py):

> [Line 176:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/log2Report/generateCompareReport.py#L176): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 175:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/log2Report/generateCompareReport.py#L175): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (176 > 120 characters)
> [Line 174:121](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/log2Report/generateCompareReport.py#L174): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (193 > 120 characters)
> [Line 171:38](https://github.com/avaframe/AvaFrame/blob/4a623b1733aa93806c63f5fa4b093ec1f71eb245/avaframe/log2Report/generateCompareReport.py#L171): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 162: [...]

2021-04-07 14:38 UTC, awirb requested changes

2021-04-07 14:39 UTC, awirb commented
and figures for aimec output in the comparison report are not always using whole space

2021-04-07 14:49 UTC, matthiasto commented on avaframe/runComparisonModules.py
> +outNew = 'OutputsFloatAllSamos'
samos refers to the friction model

2021-04-07 14:50 UTC, matthiasto commented on avaframe/runComparisonModules.py
> +        cfgRep = cfgUtils.getModuleConfig(generateCompareReport)
I thought we should not change ini variables in the code

2021-04-07 14:51 UTC, matthiasto commented on avaframe/com1DFA/com1DFA.py
> +        startTime = time.time()
each para variation will get it own time

2021-04-08 07:18 UTC, awirb commented on avaframe/runComparisonModules.py
> +        cfgRep = cfgUtils.getModuleConfig(generateCompareReport)
I would think it is ok for a runscript with a specific purpose, no?

2021-04-08 07:18 UTC, awirb commented on avaframe/com1DFA/com1DFA.py
> +        startTime = time.time()
yes but in case of parameterVar, also the project creation is timed, if not used then only the null sim is timed but not the project creation

2021-04-08 07:40 UTC, merged