Compare ent res simulations
avaframe/AvaFrame pull request #385
Opened 2021-04-09 09:37 UTC by matthiasto

Allow to compare entrainment simulations
Fix blank space above figure

2021-04-09 09:37 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/ana3AIMEC/aimecTools.py`](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/aimecTools.py):

> [Line 205:133](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/aimecTools.py#L205): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 205:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/aimecTools.py#L205): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (191 > 120 characters)
> [Line 59:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/aimecTools.py#L59): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 50:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/aimecTools.py#L50): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)

* In the file [`avaframe/ana3AIMEC/ana3AIMEC.py`](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/ana3AIMEC.py):

> [Line 454:31](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/ana3AIMEC.py#L454): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 450:32](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/ana3AIMEC.py#L450): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 399:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/ana3AIMEC.py#L399): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (143 > 120 characters)
> [Line 396:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/ana3AIMEC.py#L396): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 319:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/ana3AIMEC.py#L319): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (143 > 120 characters)
> [Line 316:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/ana3AIMEC.py#L316): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 189:70](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/ana3AIMEC.py#L189): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

* In the file [`avaframe/ana3AIMEC/dfa2Aimec.py`](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/dfa2Aimec.py):

> [Line 174:31](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/dfa2Aimec.py#L174): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 161:54](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/dfa2Aimec.py#L161): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 106:1](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/ana3AIMEC/dfa2Aimec.py#L106): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`avaframe/com1DFAPy/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py):

> [Line 1754:17](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L1754): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 1725:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L1725): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 120 characters)
> [Line 1725:120](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L1725): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1718:59](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L1718): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1717:138](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L1717): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1717:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L1717): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (152 > 120 characters)
> [Line 1710:83](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L1710): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1710:53](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L1710): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 737:9](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L737): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 479:39](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L479): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ':'
> [Line 328:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L328): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (165 > 120 characters)
> [Line 146:56](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L146): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 137:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L137): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 118:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L118): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 120 characters)
> [Line 106:121](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/com1DFAPy/com1DFA.py#L106): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)

* In the file [`avaframe/out3Plot/outAIMEC.py`](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/out3Plot/outAIMEC.py):

> [Line 611:46](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/out3Plot/outAIMEC.py#L611): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 605:13](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/out3Plot/outAIMEC.py#L605): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 601:13](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466dca940c8a9a6f6b2/avaframe/out3Plot/outAIMEC.py#L601): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 597:13](https://github.com/avaframe/AvaFrame/blob/c11d296b6f1eaf9f8e972466 [...]

2021-04-12 06:30 UTC, awirb requested changes

2021-04-13 07:53 UTC, fso42 requested changes

2021-04-13 07:53 UTC, fso42 commented on avaframe/ana3AIMEC/ana3AIMEC.py
> +        releaseMass, entrainedMass, entMassArray, totalMassArray, finalMass, relativMassDiff, grIndex, grGrad, time = aT.analyzeMass(fnameMass)
please see issue #357

2021-04-13 07:53 UTC, fso42 commented on avaframe/out3Plot/outAIMEC.py
> +    axes.flatten()[1].text(time[-1]/4, (np.nanmin(totalMassArray[0, :])+np.nanmax(totalMassArray[0, :]))/2, 'Entrained Mass Difference : %.2f kg \n Relative to entrained mass : %.2f %% \n Relative to
```suggestion
    axes.flatten()[1].text(time[-1]/4, (np.nanmin(totalMassArray[0, :])+np.nanmax(totalMassArray[0, :]))/2, 
                                    'Entrained Mass Difference : %.2f kg \n Relative to entrained mass : %.2f %% \n Relative to total mass : %.2f %% ' %
```

2021-04-13 07:53 UTC, fso42 commented on avaframe/out3Plot/outAIMEC.py
> +    y_lim = min(np.nanmax(runoutLength)+20, s[-1])
```suggestion
    yLim = min(np.nanmax(runoutLength)+20, s[-1])
```

2021-04-13 07:53 UTC, fso42 commented on avaframe/out3Plot/outAIMEC.py
> +                         extent=[l.min(), l.max(), 0, y_lim],
```suggestion
                         extent=[l.min(), l.max(), 0, yLim],
```

2021-04-13 07:53 UTC, fso42 commented on avaframe/out3Plot/outAIMEC.py
> +                         extent=[l.min(), l.max(), s[indStartOfRunout:].min(), y_lim],
```suggestion
                         extent=[l.min(), l.max(), s[indStartOfRunout:].min(), yLim],
```

2021-04-13 07:53 UTC, fso42 commented on avaframe/out3Plot/outAIMEC.py
> +
Please make a small internal function for the repetitive part...

2021-04-15 08:13 UTC, awirb requested changes
* adjust yLim of plots to display all the difference data

2021-04-15 09:18 UTC, merged