Update docu about quick plot function
avaframe/AvaFrame pull request #399
Opened 2021-04-19 06:14 UTC by awirb

2021-04-19 06:14 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/out3Plot/outQuickPlot.py`](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py):

> [Line 503:5](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L503): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 420:1](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L420): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 298:121](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L298): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 120 characters)
> [Line 292:30](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L292): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 236:121](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L236): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 219:121](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L219): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 218:121](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L218): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 153:69](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L153): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 153:42](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L153): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 133:48](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L133): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 77:44](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L77): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 77:31](https://github.com/avaframe/AvaFrame/blob/a29c8523c7d908f11d7e07aaebbe55ff7d0a29e1/avaframe/out3Plot/outQuickPlot.py#L77): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-04-19 07:20 UTC, matthiasto approved these changes

2021-04-19 09:23 UTC, fso42 requested changes

2021-04-19 09:23 UTC, fso42 commented on docs/moduleOut3Plot.rst
> +The second dataset is fetched from the benchmark results or from the Outputs of a second computational module, using the same filtering characteristics.
```suggestion
The second dataset is fetched from the benchmark results or from the output of a second computational module, using the same filtering characteristics.
```

2021-04-20 07:16 UTC, fso42 approved these changes

2021-04-20 07:16 UTC, merged