Add report item and update report plots
avaframe/AvaFrame pull request #405
Opened 2021-04-20 13:44 UTC by awirb

2021-04-20 13:44 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/com1DFAPy/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py):

> [Line 1751:17](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L1751): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 1722:121](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L1722): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 120 characters)
> [Line 1722:120](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L1722): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1715:59](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L1715): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1714:138](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L1714): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1714:121](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L1714): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (152 > 120 characters)
> [Line 1707:83](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L1707): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1707:53](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L1707): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 1267:39](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L1267): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 744:9](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L744): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 496:67](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L496): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ':'
> [Line 361:48](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L361): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 339:36](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L339): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 142:121](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L142): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 120 characters)
> [Line 123:121](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L123): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (138 > 120 characters)
> [Line 114:13](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L114): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 107:121](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L107): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)
> [Line 77:6](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L77): [E116](https://duckduckgo.com/?q=pep8%20E116) unexpected indentation (comment)
> [Line 77:6](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/com1DFAPy/com1DFA.py#L77): [E114](https://duckduckgo.com/?q=pep8%20E114) indentation is not a multiple of four (comment)

* In the file [`avaframe/out1Peak/outPlotAllPeak.py`](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/out1Peak/outPlotAllPeak.py):

> [Line 110:121](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/out1Peak/outPlotAllPeak.py#L110): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 120 characters)
> [Line 109:121](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/out1Peak/outPlotAllPeak.py#L109): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (146 > 120 characters)
> [Line 80:28](https://github.com/avaframe/AvaFrame/blob/50b4e731eed538c2a543c4f76c340a48db036690/avaframe/out1Peak/outPlotAllPeak.py#L80): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-04-21 07:32 UTC, matthiasto requested changes

2021-04-21 07:32 UTC, matthiasto commented on avaframe/out1Peak/outPlotAllPeak.py
> +        data = np.ma.masked_where(dataConstrained == 0.0, dataConstrained)
it would be interesting to have this in a separate function that we can use in other plots!!

2021-04-21 08:35 UTC, fso42 requested changes

2021-04-21 08:35 UTC, fso42 commented on avaframe/com1DFAPy/com1DFA.py
> +def reportAddInfo(reportDict, tcpuDFA, cfgGen, stopCritNotReached, avaTime, infoDict):
rename to `reportAddTimeMassInfo`

2021-04-21 08:35 UTC, fso42 commented on avaframe/out3Plot/plotUtilsCfg.ini
> +plotBuffer = 50
I suggest setting this to 150 by default

2021-04-21 09:29 UTC, matthiasto approved these changes

2021-04-21 09:46 UTC, fso42 approved these changes

2021-04-21 10:02 UTC, merged