Test drop
avaframe/AvaFrame pull request #447
Opened 2021-05-27 08:35 UTC by matthiasto

Add the step option to generate topography
Add parabola and hockey with a step/drop and three release areas
Enable the filehandler to treat empty fields in the ini file (for example resType)
Make Aimec work for multiple release scenarios in the runComparisonModules.py

2021-05-27 08:35 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py):

> [Line 458:5](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L458): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 444:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L444): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (159 > 120 characters)
> [Line 432:9](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L432): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 431:9](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L431): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 389:29](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L389): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 386:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L386): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 384:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L384): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (175 > 120 characters)
> [Line 381:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L381): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (167 > 120 characters)
> [Line 332:33](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L332): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 327:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L327): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (172 > 120 characters)
> [Line 313:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L313): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 120 characters)
> [Line 313:94](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L313): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 304:21](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L304): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 303:21](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L303): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 159:42](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFA/com1DFA.py#L159): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','

* In the file [`avaframe/com1DFAPy/DFAtools.py`](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py):

> [Line 225:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py#L225): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 211:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py#L211): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 201:29](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py#L201): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 200:29](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py#L200): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 197:29](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py#L197): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 196:29](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py#L196): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 151:29](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py#L151): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 150:29](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py#L150): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 147:29](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py#L147): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 146:29](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/DFAtools.py#L146): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator

* In the file [`avaframe/com1DFAPy/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/com1DFA.py):

> [Line 1871:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/com1DFA.py#L1871): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 1801:17](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/com1DFA.py#L1801): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 1771:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/com1DFA.py#L1771): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (139 > 120 characters)
> [Line 1763:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/com1DFA.py#L1763): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (157 > 120 characters)
> [Line 1049:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/com1DFA.py#L1049): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (140 > 120 characters)
> [Line 1047:121](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/com1DFA.py#L1047): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 120 characters)
> [Line 1044:48](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/com1DFA.py#L1044): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 939:67](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/com1DFA.py#L939): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 789:9](https://github.com/avaframe/AvaFrame/blob/1ed531867ba79118a244e7502796c610f4d7165c/avaframe/com1DFAPy/com1DFA.py#L789): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 622:29](http [...]

2021-05-27 12:13 UTC, fso42 requested changes
Those .keep files are redundant, since the folder is not empty. So please remove them.

2021-05-27 12:13 UTC, fso42 commented on avaframe/com1DFA/com1DFA.py
> +def saveMesh(avaDir, simName, dem):
please add a quick docstring

2021-05-27 12:13 UTC, fso42 commented on avaframe/com1DFAPy/DFAtools.py
> +    # A = np.where(A > 3*csz*csz, 3*csz*csz, A)
Do you really want to put this change in the master already?

2021-05-27 12:13 UTC, fso42 commented on avaframe/com1DFAPy/com1DFA.py
> +    Mesh = sorted(glob.glob(os.path.join(inDir, '*', '*.p')))
I suggest switching this to `pathlib` with eg. `Path.glob`

2021-05-27 12:13 UTC, fso42 commented on avaframe/in3Utils/generateTopo.py
> +    """ Compute coordinates of inclined plane with given slope (meanAlpha)
Please put a more extensive parameter description in the docstring

2021-05-27 12:13 UTC, fso42 commented on avaframe/in3Utils/generateTopo.py
> +    zIniDrop, _ = geoTrans.projectOnGrid(xStartDrop*np.ones((nrows)), y[:, 0], np.vstack((zv[0,:], zv)), csz=dx, xllc=x[0, 0], yllc=y[0, 0], interp='bilinear')
```suggestion
    zIniDrop, _ = geoTrans.projectOnGrid(xStartDrop*np.ones((nrows)), 
                                                                y[:, 0], np.vstack((zv[0,:], zv)), 
                                                                csz=dx, xllc=x[0, 0], yllc=y[0, 0], 
                                                                interp='bilinear')
```

2021-05-27 12:13 UTC, fso42 commented on avaframe/in3Utils/generateTopo.py
> +    zEndDrop, _ = geoTrans.projectOnGrid(xEndDrop*np.ones((nrows)), y[:, 0], np.vstack((zv[0,:], zv)), csz=dx, xllc=x[0, 0], yllc=y[0, 0], interp='bilinear')
see above

2021-05-31 15:26 UTC, awirb requested changes

2021-05-31 15:26 UTC, awirb commented on avaframe/com1DFAPy/DFAfunctionsCython.pyx
> +      uzNew = uzNew * uMag / (uMagNew + 0*velMagMin)
is this on purpose? - or can 0*velMagMin be removed?

2021-05-31 15:26 UTC, awirb commented on avaframe/in3Utils/generateTopoCfg.ini
> +# this parameter required for SP
SP?

2021-06-01 12:04 UTC, matthiasto commented
to be continued...

2021-06-01 12:04 UTC, closed without merging