change fetch benchmarks
avaframe/AvaFrame pull request #448
Opened 2021-05-31 12:06 UTC by awirb

* simplify fetching of benchmarks and finding matching simulations 
* remove multiple releaseScenarios from benchmarks 
* update benchmark json files 
* add runFetchBench.py as an example on how to fetch benchmark results 
* update runStandardTests.py and runStandardTestsPy.py

2021-05-31 12:06 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/ana1Tests/testUtilities.py`](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/ana1Tests/testUtilities.py):

> [Line 155:5](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/ana1Tests/testUtilities.py#L155): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 137:1](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/ana1Tests/testUtilities.py#L137): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 117:22](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/ana1Tests/testUtilities.py#L117): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 116:18](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/ana1Tests/testUtilities.py#L116): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 116:18](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/ana1Tests/testUtilities.py#L116): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 64:5](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/ana1Tests/testUtilities.py#L64): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 39:35](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/ana1Tests/testUtilities.py#L39): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 27:17](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/ana1Tests/testUtilities.py#L27): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent



* In the file [`avaframe/in3Utils/cfgUtils.py`](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/in3Utils/cfgUtils.py):

> [Line 428:40](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/in3Utils/cfgUtils.py#L428): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 424:5](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/in3Utils/cfgUtils.py#L424): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 92:37](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/in3Utils/cfgUtils.py#L92): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator

* In the file [`avaframe/log2Report/generateCompareReport.py`](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py):

> [Line 181:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py#L181): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 180:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py#L180): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (176 > 120 characters)
> [Line 179:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py#L179): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (193 > 120 characters)
> [Line 176:38](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py#L176): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 167:9](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py#L167): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 154:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py#L154): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 112:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py#L112): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 44:1](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py#L44): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 37:23](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py#L37): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 23:19](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/log2Report/generateCompareReport.py#L23): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator

* In the file [`avaframe/out3Plot/outQuickPlot.py`](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py):

> [Line 579:5](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L579): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 496:1](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L496): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 378:35](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L378): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 347:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L347): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 330:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L330): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 298:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L298): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 120 characters)
> [Line 292:30](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L292): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 236:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L236): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 219:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L219): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 218:121](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L218): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 153:69](https://github.com/avaframe/AvaFrame/blob/9b13e149ff05f3aaf0fedab303d9b7f6d2f11be1/avaframe/out3Plot/outQuickPlot.py#L153): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 153:42](https://github.com/avaframe/AvaFrame/blob/9b1 [...]

2021-06-01 06:56 UTC, fso42 requested changes
Please address those mixed spaces/tabs warnings (pep8speaks) -> only use spaces

2021-06-01 11:16 UTC, fso42 approved these changes

2021-06-02 09:01 UTC, matthiasto approved these changes

2021-06-02 09:18 UTC, merged