Check curvature and reprojection
avaframe/AvaFrame pull request #449
Opened 2021-06-01 12:05 UTC by matthiasto

Add samos reprojection method

2021-06-01 12:05 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py):

> [Line 459:5](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L459): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 445:121](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L445): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (159 > 120 characters)
> [Line 433:9](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L433): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 432:9](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L432): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 390:29](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L390): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 387:121](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L387): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 385:121](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L385): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (175 > 120 characters)
> [Line 382:121](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L382): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (167 > 120 characters)
> [Line 332:33](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L332): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 327:121](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L327): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (172 > 120 characters)
> [Line 313:121](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L313): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 120 characters)
> [Line 313:94](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L313): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 304:21](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L304): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 303:21](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L303): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 159:42](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/com1DFA/com1DFA.py#L159): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','

* In the file [`avaframe/in3Utils/fileHandlerUtils.py`](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py):

> [Line 471:24](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L471): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 470:78](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L470): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 457:43](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L457): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 420:18](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L420): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 403:121](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L403): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 399:22](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L399): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 388:18](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L388): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 342:30](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L342): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 297:36](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L297): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 151:37](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L151): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 131:5](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L131): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 67:68](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L67): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 67:39](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L67): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 67:23](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/in3Utils/fileHandlerUtils.py#L67): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'

* In the file [`avaframe/out3Plot/outQuickPlot.py`](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/out3Plot/outQuickPlot.py):

> [Line 510:5](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/out3Plot/outQuickPlot.py#L510): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 427:1](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/out3Plot/outQuickPlot.py#L427): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 303:121](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/out3Plot/outQuickPlot.py#L303): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 120 characters)
> [Line 297:30](https://github.com/avaframe/AvaFrame/blob/828188c95b70a728a6c30c6cd9246a950109aa59/avaframe/out3Plot/outQuickPlot.py#L297): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 241:121](https://github.c [...]

2021-06-02 08:01 UTC, fso42 requested changes

2021-06-02 08:01 UTC, fso42 commented on avaframe/com1DFAPy/DFAfunctionsCython.pyx
> +cdef (double, double, int, int, int, int, double, double, double, double) normalProjectionIteratrive(double xOld, double yOld, double zOld, double[:,:] ZDEM, double[:,:] Nx, double[:,:] Ny, double[:,
Break the line

2021-06-02 08:01 UTC, fso42 commented on avaframe/com1DFAPy/DFAfunctionsCython.pyx
> +cdef (double, double, double) getVector(int Lxy0, int Lxy1, int Lxy2, int Lxy3, double w0, double w1, double w2, double w3, double[:, :] Nx, double[:, :] Ny, double[:, :] Nz):
break the line

2021-06-02 09:20 UTC, matthiasto commented on avaframe/com1DFAPy/DFAfunctionsCython.pyx
> +  cdef double[:] Z = particles['z']
upper case is for arrays and lower case for single values in the array, is that a problem?

2021-06-02 09:29 UTC, closed without merging