Check curvature and reprojection
avaframe/AvaFrame pull request #451
Opened 2021-06-02 09:31 UTC by matthiasto

2021-06-02 09:40 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py):

> [Line 458:5](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L458): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 444:121](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L444): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (159 > 120 characters)
> [Line 432:9](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L432): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 431:9](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L431): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 389:29](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L389): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 386:121](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L386): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 384:121](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L384): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (175 > 120 characters)
> [Line 381:121](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L381): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (167 > 120 characters)
> [Line 332:33](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L332): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 327:121](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L327): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (172 > 120 characters)
> [Line 313:121](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L313): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 120 characters)
> [Line 313:94](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L313): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 304:21](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L304): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 303:21](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L303): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 159:42](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/com1DFA/com1DFA.py#L159): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','

* In the file [`avaframe/in3Utils/fileHandlerUtils.py`](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py):

> [Line 471:24](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L471): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 470:78](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L470): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 457:43](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L457): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 420:18](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L420): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 403:121](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L403): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 399:22](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L399): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 388:18](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L388): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 342:30](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L342): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 297:36](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L297): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 151:37](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L151): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 131:5](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L131): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 67:68](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L67): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 67:39](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L67): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 67:23](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/in3Utils/fileHandlerUtils.py#L67): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'

* In the file [`avaframe/out3Plot/outQuickPlot.py`](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/out3Plot/outQuickPlot.py):

> [Line 387:35](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/out3Plot/outQuickPlot.py#L387): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 305:121](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/out3Plot/outQuickPlot.py#L305): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 120 characters)
> [Line 223:121](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/out3Plot/outQuickPlot.py#L223): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 158:44](https://github.com/avaframe/AvaFrame/blob/a8b4ea778769e79f6c987f886e242873cc407758/avaframe/out3Plot/outQuickPlot.py#L158): [E225](https://duckduckgo.com/?q=pep8%20E22 [...]

2021-06-02 13:54 UTC, awirb requested changes

2021-06-04 06:11 UTC, awirb requested changes

2021-06-04 06:11 UTC, awirb commented on avaframe/com1DFAPy/DFAfunctionsCython.pyx
> +    nx, ny, nz = getVector(Lxy[0], Lxy[1], Lxy[2], Lxy[3], 0.25, 0.25, 0.25, 0.25, nxArray, nyArray, nzArray)
if both option, flag in ini file?

2021-06-07 06:28 UTC, fso42 approved these changes

2021-06-07 06:44 UTC, merged