Release polygon
avaframe/AvaFrame pull request #458
Opened 2021-06-09 10:01 UTC by matthiasto

New method to get the release area:
First get the cells for which the center lies inside the polygon. Check overlap of features
Then do the same thing but include all cells that touch the release polygon.
Use this to generate the particles. Then remove particles that lay outside the release polygon.
This way we should get very close to the expected release are!

2021-06-09 10:01 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/DFAtools.py`](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py):

> [Line 225:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py#L225): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 211:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py#L211): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 201:29](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py#L201): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 200:29](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py#L200): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 197:29](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py#L197): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 196:29](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py#L196): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 151:29](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py#L151): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 150:29](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py#L150): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 147:29](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py#L147): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 146:29](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/DFAtools.py#L146): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py):

> [Line 1982:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L1982): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 1912:17](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L1912): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 1882:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L1882): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (139 > 120 characters)
> [Line 1874:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L1874): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (157 > 120 characters)
> [Line 1396:63](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L1396): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 1060:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L1060): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (140 > 120 characters)
> [Line 1058:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L1058): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 120 characters)
> [Line 1055:48](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L1055): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 950:67](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L950): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 798:9](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L798): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 609:29](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L609): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 608:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L608): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 606:41](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L606): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '('
> [Line 537:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L537): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 530:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L530): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 509:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L509): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (143 > 120 characters)
> [Line 505:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L505): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 120 characters)
> [Line 487:67](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L487): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ':'
> [Line 474:121](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L474): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 321:36](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L321): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 174:5](https://github.com/avaframe/AvaFrame/blob/023457f0283d2c4615f10ca4f9f7d1548b03c1ae/avaframe/com1DFA/com1DFA.py#L174): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)



Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-06-09 13:47 UTC, awirb requested changes

2021-06-09 14:03 UTC, fso42 requested changes

2021-06-09 14:03 UTC, fso42 commented on avaframe/in2Trans/shpConversion.py
> +    """ Remove feature number nFeature2Remove from featureIn"""
please include the type of input expected (in the docstring)

2021-06-09 14:03 UTC, fso42 commented on avaframe/in2Trans/shpConversion.py
> +    """ Extract feature nFeature2Extract from featureIn"""
same as above

2021-06-10 06:01 UTC, matthiasto commented on avaframe/com1DFA/com1DFA.py
> +def prepareArea(line, dem, radius, thList='', combine=True, checkOverlap=True):
yes I need it to know if I return an error in case of overlap or not. We could decide never to return the error, just a warning

2021-06-10 06:28 UTC, matthiasto commented on avaframe/com1DFA/com1DFA.py
> +    prepareArea(releaseLine, demOri, 0.001, combine=True, checkOverlap=True)
This is just a super small value in order to catch the points laying exactly on the polygon. is it really necessary to have it in the ini file?

2021-06-10 06:47 UTC, awirb requested changes

2021-06-10 06:47 UTC, awirb commented on avaframe/com1DFA/com1DFA.py
> +    prepareArea(releaseLine, demOri, cfgGen.getfloat(radiusPolygon), combine=True, checkOverlap=True)
I thin this needs quotes 'radiusPolygon'  and is it in the ini?

2021-06-10 09:04 UTC, fso42 commented on avaframe/com1DFA/com1DFA.py
> +    prepareArea(releaseLine, demOri, 0.001, combine=True, checkOverlap=True)
Any (adjustable) setting should go into the ini! I think is really important, even if it seems to be an 'unnecessary' parameter...

2021-06-10 10:21 UTC, fso42 approved these changes

2021-06-10 11:02 UTC, merged