fixing find beta angle issue
avaframe/AvaFrame pull request #463
Opened 2021-06-11 05:48 UTC by matthiasto

Finding the beta angle did not work when the profile is very finely resampled or has uneven steps.
We now use a given threshold defined in the ini file to determine how many point (how much distance) has to be bellow the Angle in order to define a point as beta point

2021-06-11 05:48 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/ana3AIMEC/aimecTools.py`](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py):

> [Line 719:47](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py#L719): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 718:46](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py#L718): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 717:49](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py#L717): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 716:58](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py#L716): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 569:121](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py#L569): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 203:133](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py#L203): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 203:121](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py#L203): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (191 > 120 characters)
> [Line 196:58](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py#L196): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 60:121](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 51:121](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/ana3AIMEC/aimecTools.py#L51): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)

* In the file [`avaframe/com2AB/com2AB.py`](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/com2AB/com2AB.py):

> [Line 244:121](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/com2AB/com2AB.py#L244): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 226:121](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/com2AB/com2AB.py#L226): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (139 > 120 characters)
> [Line 190:26](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/com2AB/com2AB.py#L190): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 149:58](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/com2AB/com2AB.py#L149): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 145:58](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/com2AB/com2AB.py#L145): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

* In the file [`avaframe/in3Utils/geoTrans.py`](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/in3Utils/geoTrans.py):

> [Line 713:121](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/in3Utils/geoTrans.py#L713): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 659:121](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/in3Utils/geoTrans.py#L659): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (147 > 120 characters)
> [Line 214:121](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/in3Utils/geoTrans.py#L214): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 37:49](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/in3Utils/geoTrans.py#L37): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 36:49](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/in3Utils/geoTrans.py#L36): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

* In the file [`avaframe/tests/test_com2AB.py`](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py):

> [Line 185:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L185): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 184:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L184): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 183:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L183): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 182:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L182): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 180:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L180): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 179:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L179): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 178:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L178): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 177:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L177): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 138:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L138): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 137:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L137): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 136:17](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L136): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 108:13](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L108): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 107:13](https://github.com/avaframe/AvaFrame/blob/b4718237d795f5fb323981ebf602dec725b00a64/avaframe/tests/test_com2AB.py#L107): [E126] [...]

2021-06-14 07:11 UTC, fso42 approved these changes

2021-06-14 07:11 UTC, fso42 commented on avaframe/in3Utils/geoTrans.py
> +    ----------
formatting error?

2021-06-14 07:48 UTC, awirb requested changes

2021-06-14 07:55 UTC, merged