Aimec error message
avaframe/AvaFrame pull request #476
Opened 2021-06-22 13:02 UTC by matthiasto

Cleaning log outputs
Printing warning if no data reached the runout zone (also in the plot)

2021-06-22 13:02 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/ana3AIMEC/aimecTools.py`](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py):

> [Line 719:47](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py#L719): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 718:46](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py#L718): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 717:49](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py#L717): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 716:58](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py#L716): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 569:121](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py#L569): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 203:128](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py#L203): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 203:121](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py#L203): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (186 > 120 characters)
> [Line 196:58](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py#L196): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 60:121](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 51:121](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/ana3AIMEC/aimecTools.py#L51): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)

* In the file [`avaframe/out3Plot/outAIMEC.py`](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py):

> [Line 649:46](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L649): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 643:13](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L643): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 639:13](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L639): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 635:13](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L635): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 620:13](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L620): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 523:121](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L523): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (136 > 120 characters)
> [Line 523:88](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L523): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 516:20](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L516): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 514:41](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L514): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 514:34](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L514): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 507:121](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L507): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (131 > 120 characters)
> [Line 507:50](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L507): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 504:38](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L504): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 503:38](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L503): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 498:79](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L498): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 498:61](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L498): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 496:128](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L496): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 496:121](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L496): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 120 characters)
> [Line 480:45](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L480): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 480:38](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L480): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 478:45](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L478): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 478:38](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L478): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 471:48](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L471): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 470:49](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L470): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 470:33](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b344102990ce418f5/avaframe/out3Plot/outAIMEC.py#L470): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 449:37](https://github.com/avaframe/AvaFrame/blob/cb7c17e5bb00a59fed0eaf5b3441 [...]

2021-06-22 15:26 UTC, awirb requested changes

2021-06-22 17:59 UTC, fso42 requested changes

2021-06-22 17:59 UTC, fso42 commented on avaframe/runAna3AIMECCompMods.py
> +compList = [['relAlr', 'null']]#, ['relKot', 'ent']]
Is that comment needed?

2021-06-23 10:55 UTC, fso42 approved these changes

2021-06-24 13:46 UTC, awirb requested changes

2021-06-24 13:46 UTC, awirb commented on avaframe/out3Plot/outAIMEC.py
> +    print(cfgPath['colorParameter'][0], typeCP)
maybe remove

2021-06-25 05:53 UTC, merged