Test drop
avaframe/AvaFrame pull request #490
Opened 2021-07-07 13:16 UTC by matthiasto

add drop option in the generateTopo
Add reprojection option in com1DFA

2021-07-07 13:16 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 



* In the file [`avaframe/ana1Tests/damBreak.py`](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py):

> [Line 255:5](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L255): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 253:20](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L253): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 251:20](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L251): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 249:27](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L249): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 243:20](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L243): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 241:30](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L241): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 241:20](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L241): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 239:20](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L239): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 237:27](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L237): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 163:8](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L163): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 162:8](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L162): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 157:22](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L157): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 142:5](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L142): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 96:24](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L96): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 79:27](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L79): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 78:27](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L78): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 34:22](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L34): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:22](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 32:37](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L32): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\p'
> [Line 32:26](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/damBreak.py#L32): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\d'

* In the file [`avaframe/ana1Tests/simiSol.py`](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py):

> [Line 624:5](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L624): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 612:40](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L612): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 612:21](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L612): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 611:40](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L611): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 611:21](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L611): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 608:121](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L608): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 608:78](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L608): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 607:78](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L607): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 603:47](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L603): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 603:28](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L603): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 602:47](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L602): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 602:28](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L602): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 599:121](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L599): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 599:85](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L599): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 598:85](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L598): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 593:5](https://github.com/avaframe/AvaFrame/blob/eb95eebeec41cc967b0d086477a2b75628847664/avaframe/ana1Tests/simiSol.py#L593): [E303](https://duckduckgo.com/?q=pep8%20E30 [...]

2021-07-08 11:02 UTC, awirb requested changes

2021-07-08 11:08 UTC, matthiasto commented on avaframe/com1DFA/DFAfunctionsCython.pyx
> +    zNoReproj = zNew
REMOVE

2021-07-08 11:13 UTC, awirb requested changes

2021-07-08 11:13 UTC, awirb commented on avaframe/com1DFA/com1DFA.py
> +from matplotlib.patches import Ellipse, Circle
remove this if unused

2021-07-08 11:13 UTC, awirb commented on avaframe/com1DFA/com1DFA.py
> +flagRand = True
please rebase with master

2021-07-12 06:39 UTC, merged