Improve cmaps
avaframe/AvaFrame pull request #496
Opened 2021-07-09 09:16 UTC by matthiasto

Refactor the makeColorMap function

2021-07-09 09:16 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py):

> [Line 2022:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L2022): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 1952:17](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L1952): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 1922:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L1922): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (140 > 120 characters)
> [Line 1914:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L1914): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (158 > 120 characters)
> [Line 1434:63](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L1434): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 1095:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L1095): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (140 > 120 characters)
> [Line 1093:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L1093): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 120 characters)
> [Line 1090:48](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L1090): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1038:37](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L1038): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1019:60](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L1019): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 981:76](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L981): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 806:9](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L806): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 612:29](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L612): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 611:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L611): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 609:41](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L609): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '('
> [Line 540:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L540): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (148 > 120 characters)
> [Line 533:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L533): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 527:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L527): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (141 > 120 characters)
> [Line 512:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L512): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (143 > 120 characters)
> [Line 508:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L508): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 120 characters)
> [Line 490:67](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L490): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ':'
> [Line 477:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L477): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 323:36](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L323): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 176:5](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/com1DFA/com1DFA.py#L176): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

* In the file [`avaframe/out1Peak/outPlotAllPeak.py`](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out1Peak/outPlotAllPeak.py):

> [Line 180:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out1Peak/outPlotAllPeak.py#L180): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (146 > 120 characters)
> [Line 169:29](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out1Peak/outPlotAllPeak.py#L169): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 102:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out1Peak/outPlotAllPeak.py#L102): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (144 > 120 characters)
> [Line 101:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out1Peak/outPlotAllPeak.py#L101): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (146 > 120 characters)
> [Line 95:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out1Peak/outPlotAllPeak.py#L95): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)

* In the file [`avaframe/out3Plot/outAIMEC.py`](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out3Plot/outAIMEC.py):

> [Line 817:26](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out3Plot/outAIMEC.py#L817): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 783:26](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out3Plot/outAIMEC.py#L783): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 735:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out3Plot/outAIMEC.py#L735): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (159 > 120 characters)
> [Line 730:121](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out3Plot/outAIMEC.py#L730): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 730:100](https://github.com/avaframe/AvaFrame/blob/94bfe1da9b49e6e5910a7715dffa1106e954b416/avaframe/out3Plot/outAIMEC.py#L730): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around  [...]

2021-07-12 09:11 UTC, awirb requested changes

2021-07-12 09:11 UTC, awirb commented on avaframe/out3Plot/plotUtils.py
> +    dictionary, the cmap is created and the levelsNew and colorsNew are created.
suggestion: 
Options: 
1. colormapDict = dict (details see Parameters) - depending on the continuous flag and what is given in the colormapDict dictionary, the cmap is created and the levelsNew and colorsNew are created.
2. colormapDict = matplotlib cmap - the continuous flag is ignored and a continuous cmap is returned with
    levelsNew and colorsNew set to None.

2021-07-12 09:11 UTC, awirb commented on avaframe/out3Plot/plotUtils.py
> +            levels: list
if colormap= dict , add this info before listing the dict keys

2021-07-12 09:11 UTC, awirb commented on avaframe/out3Plot/plotUtils.py
> +            norm associated to the levels and the colors (None for continuous=True)
please update

2021-07-12 09:11 UTC, awirb commented on avaframe/out3Plot/plotUtils.py
> +        # do we have a cmap in the dict?
suggestion: check if cmap is provided

2021-07-12 09:11 UTC, awirb commented on avaframe/out3Plot/plotUtils.py
> +        # if not do we have a list of colors in the dict?
check if list of colors is provided

2021-07-12 09:11 UTC, awirb commented on avaframe/out3Plot/plotUtils.py
> +        # do we have a list of colors in the dict?
same here

2021-07-12 09:11 UTC, awirb commented on avaframe/out3Plot/plotUtils.py
> +            # cmap.set_over(color='w')
still needed?

2021-07-12 09:11 UTC, awirb commented on avaframe/out3Plot/plotUtils.py
> +        # if not do we have a cmap in the dict?
check if a cmap is provided

2021-07-13 07:25 UTC, fso42 approved these changes

2021-07-13 07:25 UTC, fso42 commented on avaframe/out3Plot/plotUtils.py
> +# cmapdiv = cmapCameri.vik
Please remove.

2021-07-13 08:31 UTC, merged