Remove particles clean
avaframe/AvaFrame pull request #498
Opened 2021-07-15 10:16 UTC by matthiasto

Remove Particles in a nicer way. 
Avoid possibility of segfault because particles exit too quickly the domain.
Remove particles both that exit the domain and that enter no data zones

2021-07-15 12:46 UTC, pep8speaks commented
Hello @matthiasto! Thanks for updating this PR. 

* In the file [`avaframe/com1DFA/DFAtools.py`](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py):

> [Line 225:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py#L225): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 211:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py#L211): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 201:29](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py#L201): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 200:29](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py#L200): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 197:29](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py#L197): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 196:29](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py#L196): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 151:29](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py#L151): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 150:29](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py#L150): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 147:29](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py#L147): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 146:29](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/DFAtools.py#L146): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py):

> [Line 2034:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L2034): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 1964:17](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L1964): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 1934:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L1934): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (140 > 120 characters)
> [Line 1926:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L1926): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (158 > 120 characters)
> [Line 1446:63](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L1446): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 1102:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L1102): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (140 > 120 characters)
> [Line 1100:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L1100): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 120 characters)
> [Line 1097:48](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L1097): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1085:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L1085): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (138 > 120 characters)
> [Line 1041:37](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L1041): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 1023:60](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L1023): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 984:76](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L984): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 808:9](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L808): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 613:29](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L613): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 612:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L612): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 610:41](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L610): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '('
> [Line 541:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L541): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (148 > 120 characters)
> [Line 534:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L534): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 528:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L528): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (141 > 120 characters)
> [Line 513:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L513): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (143 > 120 characters)
> [Line 509:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L509): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (134 > 120 characters)
> [Line 491:67](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L491): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ':'
> [Line 478:121](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L478): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 323:36](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L323): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 176:5](https://github.com/avaframe/AvaFrame/blob/6e8fd4c9bd1c40310870cebd29c7b2df3f600fa1/avaframe/com1DFA/com1DFA.py#L176): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

* In the file [`avaframe/runScrip [...]

2021-07-16 08:07 UTC, fso42 requested changes

2021-07-16 08:07 UTC, fso42 commented on avaframe/com1DFA/com1DFA.py
> +# matplotlib.use('agg')
please leave this activated

2021-07-16 08:07 UTC, fso42 commented on avaframe/com1DFA/com1DFA.py
> +    log.info(('cpu time total other = %s s' % ((Tcpu['Force'] + Tcpu['ForceSPH'] + Tcpu['Pos'] + Tcpu['Neigh'] + Tcpu['Field']) / nIter)))
Please break this line

2021-07-16 08:07 UTC, fso42 commented on avaframe/tests/test_SPHfunctionsCython.py
> +        xpn, ypn, iCell, Lx0, Ly0, w0, w1, w2, w3 = DFAfunC.samosProjectionIteratrive(x1, y1, z1, ZZ, Nx, Ny, Nz, csz, ncols, nrows, interpOption, reprojectionIterations)
please break this and similar lines

2021-07-16 12:04 UTC, awirb requested changes

2021-07-16 13:39 UTC, merged