Aimec in out
avaframe/AvaFrame pull request #622
Opened 2021-12-21 15:29 UTC by matthiasto

In this PR we modify the way aimec gets its inputs and the way it returns the outputs.
The inputs are now stored in a dataframe (containing for each simulation the type, name, release... and the available peak fields path: ppr....) 
pathDict is still a dict but contains only info about the dem path, the shp files and the reference simulation

The reference is processed first, then all the other sims are processed, one after the other and compared to the reference.
This avoids storing a big amount of data (only the essential final results from the analysis are stored and saved to a csv file) This file can be then reloaded in order to do more specific/advanced plots

For now, only aimec for com1DFA can be used.
After feed back is given, I will adapt the aimec report and indi versions

2021-12-21 15:29 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/ana3AIMEC/aimecTools.py`](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/aimecTools.py):

> [Line 573:121](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/aimecTools.py#L573): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 236:51](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/aimecTools.py#L236): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 135:121](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/aimecTools.py#L135): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 135:75](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/aimecTools.py#L135): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 117:121](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/aimecTools.py#L117): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 120 characters)
> [Line 106:25](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/aimecTools.py#L106): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 106:25](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/aimecTools.py#L106): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

* In the file [`avaframe/ana3AIMEC/ana3AIMEC.py`](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/ana3AIMEC.py):

> [Line 170:121](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/ana3AIMEC.py#L170): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (155 > 120 characters)
> [Line 164:121](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/ana3AIMEC.py#L164): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (157 > 120 characters)
> [Line 69:64](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/ana3AIMEC.py#L69): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','

* In the file [`avaframe/ana3AIMEC/dfa2Aimec.py`](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/dfa2Aimec.py):

> [Line 152:18](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/dfa2Aimec.py#L152): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 147:5](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/ana3AIMEC/dfa2Aimec.py#L147): [E129](https://duckduckgo.com/?q=pep8%20E129) visually indented line with same indent as next logical line

* In the file [`avaframe/in3Utils/fileHandlerUtils.py`](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py):

> [Line 641:43](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L641): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 635:30](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L635): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 564:78](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L564): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 555:43](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L555): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 516:18](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L516): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 495:22](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L495): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 484:18](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L484): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 420:62](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L420): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 411:49](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L411): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 391:30](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L391): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 280:5](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L280): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 227:37](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L227): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 88:68](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L88): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 88:39](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L88): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 88:23](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/fileHandlerUtils.py#L88): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'

* In the file [`avaframe/in3Utils/initializeProject.py`](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/initializeProject.py):

> [Line 95:8](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/initializeProject.py#L95): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'
> [Line 61:8](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/in3Utils/initializeProject.py#L61): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'

* In the file [`avaframe/out3Plot/outAIMEC.py`](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/out3Plot/outAIMEC.py):

> [Line 809:121](https://github.com/avaframe/AvaFrame/blob/828526e8f5199af1df85bc799061604129dec8c2/avaframe/out3Plot/outAIMEC.py#L809): [E501](https://duckduckgo.com/?q=pep8%20E501) l [...]

2021-12-29 18:01 UTC, fso42 requested changes

2021-12-29 18:01 UTC, fso42 commented on avaframe/out3Plot/outAIMEC.py
> +    if (nSim > 100):
we missed this one earlier: this needs to be a ini parameter

2022-01-03 06:26 UTC, matthiasto commented on avaframe/ana3AIMEC/aimecTools.py
> +            colorParameter = True
we need to define a reference simulation for the aimec comparison. Where should we do this then?

2022-01-03 06:36 UTC, matthiasto commented on avaframe/ana3AIMEC/aimecTools.py
> +        type of the data to analyze ('ppr', 'pfd' or 'pfv')
you need to specify what data type the function analyze fields is processing. It can indeed be everything you like.

2022-01-03 10:44 UTC, fso42 commented on avaframe/ana3AIMEC/aimecTools.py
> +            colorParameter = True
I understand that, but why is setting colors for plotting done in here, i.e. what does that have to do with definining a reference sim?

2022-01-03 15:00 UTC, awirb requested changes

2022-01-04 14:31 UTC, matthiasto commented on avaframe/ana3AIMEC/aimecTools.py
> +            colorParameter = True
only the colorParameter is actually related to ploting, the rest is there to define the reference simulation, so colorValues could be renamed to findRef or whatever to make it clear that it is nothing to do with colors

2022-01-05 09:02 UTC, fso42 requested changes

2022-01-05 09:02 UTC, fso42 commented on avaframe/runScripts/runAna3AIMECCompMods.py
> +    compList = [['relAlr1', 'null']]  # , ['relAlr', 'ent']]
Is this change actually wanted?

2022-01-05 09:02 UTC, fso42 commented on avaframe/runScripts/runAna3AIMECCompMods.py
> +        # ana3AIMEC.mainAIMEC(pathDict, cfg)
uncomment? remove?

2022-01-05 09:02 UTC, fso42 commented on avaframe/runScripts/runAna3AIMECIndi.py
> +ana3AIMEC.AIMECIndi(pathDict, inputsDF, cfg)
See renaming comment earlier, maybe rename the whole runscript as well

2022-01-05 10:18 UTC, fso42 commented
And please address the pep8 issues...

2022-01-05 14:59 UTC, matthiasto commented on avaframe/ana3AIMEC/ana3AIMEC.py
> +    # ###########################################################
will try to fix this, I then need a bit more time...

2022-01-12 16:22 UTC, awirb requested changes

2022-01-12 16:22 UTC, awirb commented on avaframe/ana3AIMEC/aimecTools.py
> +def analyzeField2(rasterTransfo, transformedRasters, dataType, resultsAreaAnalysis):
why are there two analyzeField functions?

2022-01-12 20:46 UTC, fso42 approved these changes

2022-01-13 10:12 UTC, awirb approved these changes

2022-01-13 10:14 UTC, merged