Ana1 influence test
avaframe/AvaFrame pull request #638
Opened 2022-01-14 10:20 UTC by belieresfrendo

This module developped in ana1Tests aims to run simulations and compare them.
The comparison is made according 2 parameters.
the first one will be an axis parameter, while the second one will allow to print several curves on the same graphic to see how the evolve according the first parameter.

-------------------------------
Moreover, some points are improved in this PR.
-> New script in DFA module to check if .ini files are well parametered
-> modify DFA to be able to get easily sim Hashes which has to be performed
-> change one spelling fault in a file name (initialise -> initialize)

2022-01-14 10:20 UTC, pep8speaks commented
Hello @belieresfrendo! Thanks for opening this PR. 

* In the file [`avaframe/ana1Tests/influenceTest.py`](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py):

> [Line 279:10](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L279): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 263:10](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L263): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 233:1](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L233): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 200:1](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L200): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 190:23](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L190): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 172:1](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L172): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 160:13](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L160): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 148:1](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L148): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 140:18](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L140): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 138:16](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L138): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 136:10](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L136): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 126:1](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L126): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 78:1](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L78): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 66:75](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L66): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 66:73](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L66): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 35:1](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/ana1Tests/influenceTest.py#L35): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)



* In the file [`avaframe/com1DFA/checkIniFiles.py`](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/checkIniFiles.py):

> [Line 16:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/checkIniFiles.py#L16): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (156 > 120 characters)
> [Line 10:1](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/checkIniFiles.py#L10): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/com1DFA.py):

> [Line 1806:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/com1DFA.py#L1806): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 1535:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/com1DFA.py#L1535): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 810:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/com1DFA.py#L810): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)
> [Line 671:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/com1DFA.py#L671): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)
> [Line 632:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/com1DFA.py#L632): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (159 > 120 characters)
> [Line 332:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/com1DFA.py#L332): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)
> [Line 293:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFA/com1DFA.py#L293): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)

* In the file [`avaframe/com1DFAOrig/com1DFAOrig.py`](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFAOrig/com1DFAOrig.py):

> [Line 457:5](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFAOrig/com1DFAOrig.py#L457): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 443:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFAOrig/com1DFAOrig.py#L443): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (166 > 120 characters)
> [Line 431:9](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFAOrig/com1DFAOrig.py#L431): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 430:9](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFAOrig/com1DFAOrig.py#L430): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 388:29](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFAOrig/com1DFAOrig.py#L388): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 385:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFAOrig/com1DFAOrig.py#L385): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 383:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFAOrig/com1DFAOrig.py#L383): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (175 > 120 characters)
> [Line 380:121](https://github.com/avaframe/AvaFrame/blob/0e8a62e41b2f23c3128e7f3b65f2d0081a9aed20/avaframe/com1DFAOrig/com1DFAOrig.py#L380): [E501](https://duckduckgo.com/?q=pep8%20E501)  [...]

2022-01-18 08:19 UTC, matthiasto requested changes
Your branch is not up to date with the master. Please rebase it.
I also see that the com1DFA.py and DFAFunctions.pyx have weird changes. I think you need to replace them by the ones from the master to avoid a lot of conflicts (also pay attention that your atom editor does not remove or add blank lines on its own)

2022-01-18 08:19 UTC, matthiasto commented on docs/DFAnumerics.rst
> +
I am not sure where we add this section. Remove it for now, I will take care of adding this when we get something meaningfull

2022-02-04 07:36 UTC, fso42 commented
Closing in favour of #661

2022-02-04 07:36 UTC, closed without merging