Ana1 test amaury
avaframe/AvaFrame pull request #661
Opened 2022-02-03 22:50 UTC by belieresfrendo

This module developped in ana1Tests aims to run simulations and compare them.
The comparison is made according 2 parameters.
the first one will be an axis parameter, while the second one will allow to print several curves on the same graphic to see how the evolve according the first parameter.

Moreover, some points are improved in this PR.
-> New script in DFA module to check if .ini files are well parametered
-> modify DFA to be able to get easily sim Hashes which has to be performed
-> change one spelling fault in a file name (initialise -> initialize)

2022-02-03 22:50 UTC, pep8speaks commented
Hello @belieresfrendo! Thanks for opening this PR. 

* In the file [`avaframe/ana1Tests/ana1TestsCheckIniFiles.py`](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/ana1TestsCheckIniFiles.py):

> [Line 16:121](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/ana1TestsCheckIniFiles.py#L16): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (157 > 120 characters)
> [Line 15:9](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/ana1TestsCheckIniFiles.py#L15): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented (comment)
> [Line 14:5](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/ana1TestsCheckIniFiles.py#L14): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 13:5](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/ana1TestsCheckIniFiles.py#L13): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 12:5](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/ana1TestsCheckIniFiles.py#L12): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 10:1](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/ana1TestsCheckIniFiles.py#L10): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`avaframe/ana1Tests/influenceTest.py`](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py):

> [Line 291:10](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L291): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 275:10](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L275): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 245:1](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L245): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 201:1](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L201): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 191:23](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L191): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 172:1](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L172): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 160:13](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L160): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 148:1](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L148): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 140:18](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L140): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 138:16](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L138): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 136:10](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L136): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 126:1](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L126): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 78:1](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L78): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 66:75](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L66): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 66:73](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L66): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 35:1](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/ana1Tests/influenceTest.py#L35): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)

* In the file [`avaframe/com1DFA/checkIniFiles.py`](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/checkIniFiles.py):

> [Line 16:121](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/checkIniFiles.py#L16): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (156 > 120 characters)
> [Line 10:1](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/checkIniFiles.py#L10): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/com1DFA.py):

> [Line 2124:57](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/com1DFA.py#L2124): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 2049:121](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/com1DFA.py#L2049): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 1047:5](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/com1DFA.py#L1047): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 928:121](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/com1DFA.py#L928): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)
> [Line 474:121](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/com1DFA.py#L474): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (148 > 120 characters)
> [Line 473:121](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/com1DFA.py#L473): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 120 characters)
> [Line 367:42](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/com1DFA.py#L367): [E271](https://duckduckgo.com/?q=pep8%20E271) multiple spaces after keyword
> [Line 211:121](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/com1DFA.py#L211): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 205:121](https://github.com/avaframe/AvaFrame/blob/ed917923da14a71583826d66d3e754fb2f7c3415/avaframe/com1DFA/com1DFA.py#L205): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 >  [...]

2022-02-04 10:33 UTC, matthiasto requested changes

2022-02-04 10:33 UTC, matthiasto commented on avaframe/com1DFA/com1DFA.py
> +    return IDList, simDict
I would maybe try to rename this to simHashList

2022-02-04 12:31 UTC, fso42 requested changes

2022-02-04 12:31 UTC, fso42 commented on avaframe/ana1Tests/ana1TestsCheckIniFiles.py
> +    log.info('checkIniFile function has to be set coded')
I think this is a duplicate, please remove

2022-02-04 12:31 UTC, fso42 commented on avaframe/ana1Tests/influenceTest.py
> +config.optionxform = str
please use the config reading routines from in3Utils.cfgUtils

2022-02-04 12:31 UTC, fso42 commented on avaframe/ana1Tests/influenceTest.py
> +    config.read(cfg)
see previous comment about config reading

2022-02-04 12:31 UTC, fso42 commented on avaframe/ana1Tests/influenceTest.py
> +    print('xAxisArray : ', xAxisArray)
please remove this print

2022-02-04 12:31 UTC, fso42 commented on avaframe/ana1Tests/influenceTest.py
> +    xAxisArray.sort()
Add some comments to explain what is happening here

2022-02-04 12:31 UTC, fso42 commented on avaframe/ana1Tests/influenceTest.py
> +    return simDF
If this removes this function, then fine. Otherwise mov this to an aimec module

2022-02-04 12:31 UTC, fso42 commented on avaframe/ana1Tests/influenceTest.py
> +def getSimLabel(avalancheDir, cfg, simDF, param2Study=0):
@awirb : don't we have this function already?

2022-02-04 12:31 UTC, fso42 commented on avaframe/ana1Tests/influenceTest.py
> +        log.info('It will be an option developped late sorry')
Leave this out and write
in the next log.info: For now simTypeList has to be null

2022-02-04 12:31 UTC, fso42 commented on avaframe/ana1Tests/influenceTest.py
> +        n=input()
remove this

2022-02-04 12:31 UTC, fso42 commented on avaframe/ana1Tests/influenceTest.py
> +            print(config['GENERAL'][generalParam])
remove or convert to log

2022-02-04 12:31 UTC, fso42 commented on avaframe/com1DFA/checkIniFiles.py
> +    Check if the .ini file is well parametered
```suggestion
    Check if the .ini file is consistent
```

2022-02-04 12:31 UTC, fso42 commented on avaframe/com1DFA/checkIniFiles.py
> +    # Check if Ata Parameters all well seted
```suggestion
    # Check if Ata Parameters are well set
```

2022-02-04 12:31 UTC, fso42 commented on avaframe/com1DFA/checkIniFiles.py
> +    log.info('Ata Parameters are well seted')
change this to log.debug and seted -> set

2022-02-04 12:31 UTC, fso42 commented on avaframe/com1DFA/com1DFA.py
> +                # Check if .ini files are were parametered.
```suggestion
                # Check if .ini files are consistent.
```

2022-02-04 12:31 UTC, fso42 commented on avaframe/out3Plot/outInfluenceTest.py
> +    ----------
Please add the changes as discussed in the meeting 04.02

2022-02-04 12:31 UTC, fso42 commented on avaframe/runScripts/runAna1InfluenceTest.py
> +config.optionxform = str
Again, please use the function from cfgUtils

2022-06-08 08:05 UTC, fso42 commented
Most of this code is now already implemented, therefore closing this PR. 

Thanks again for your contribution!

2022-06-08 08:05 UTC, closed without merging