Make nice plots
avaframe/AvaFrame pull request #676
Opened 2022-03-03 11:08 UTC by matthiasto

Make similarity solution presentation plots

2022-03-03 11:10 UTC, pep8speaks commented
Hello @matthiasto! Thanks for updating this PR. 

* In the file [`avaframe/out3Plot/outAna1Plots.py`](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py):

> [Line 704:39](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L704): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 703:43](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L703): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 653:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L653): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 591:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L591): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 120 characters)
> [Line 559:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L559): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 120 characters)
> [Line 531:66](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L531): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 531:66](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L531): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 530:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L530): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (136 > 120 characters)
> [Line 527:24](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L527): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 514:15](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L514): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 512:16](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L512): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 492:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L492): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 120 characters)
> [Line 433:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L433): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (193 > 120 characters)
> [Line 431:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L431): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (177 > 120 characters)
> [Line 421:58](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L421): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 421:58](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L421): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 420:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L420): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 419:57](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L419): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 419:57](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L419): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 418:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L418): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 404:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L404): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 120 characters)
> [Line 374:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L374): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 359:15](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L359): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 353:16](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L353): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 343:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L343): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (142 > 120 characters)
> [Line 320:57](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L320): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '
> [Line 320:57](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L320): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 307:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L307): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 120 characters)
> [Line 259:22](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L259): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 231:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L231): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (148 > 120 characters)
> [Line 112:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L112): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 109:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L109): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 103:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L103): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 88:121](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L88): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 84:46](https://github.com/avaframe/AvaFrame/blob/2043c150db733ae83660ad13ec4017d85259606f/avaframe/out3Plot/outAna1Plots.py#L84): [E225](https://duck [...]

2022-03-03 20:08 UTC, fso42 approved these changes
Minor changes, please fix before merging

2022-03-03 20:08 UTC, fso42 commented on avaframe/out3Plot/outAna1Plots.py
> +    # plt.show()
Is this still needed?

2022-03-03 20:08 UTC, fso42 commented on avaframe/out3Plot/outAna1Plots.py
> +                                   marker=pU.markers[0], alpha=1)#, edgecolors='k')
Either use it or remove the edgecolor comment

2022-03-04 07:49 UTC, awirb requested changes

2022-03-04 07:49 UTC, awirb commented on avaframe/out3Plot/outAna1Plots.py
> +    """
add fit parameter

2022-03-07 08:42 UTC, merged