Updates ana1Tests and doc
avaframe/AvaFrame pull request #680
Opened 2022-03-09 15:14 UTC by matthiasto

Have a look here for the new doc:
https://docs.avaframe.org/en/refactordambreak/moduleAna1Tests.html#

The flat plane test will come soon

2022-03-09 15:14 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/ana1Tests/damBreak.py`](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py):

> [Line 422:121](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L422): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 120 characters)
> [Line 417:72](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L417): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 309:121](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L309): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)
> [Line 293:121](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L293): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (141 > 120 characters)
> [Line 256:5](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L256): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 254:9](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L254): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 248:121](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L248): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 240:48](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L240): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 233:23](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L233): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 220:59](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L220): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ','
> [Line 220:39](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L220): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ','
> [Line 168:1](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L168): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 139:8](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L139): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 138:8](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L138): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 137:8](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L137): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 132:22](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L132): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 68:24](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L68): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 65:5](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L65): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 35:54](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L35): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 34:22](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L34): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:22](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/damBreak.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

* In the file [`avaframe/ana1Tests/energyLineTest.py`](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/energyLineTest.py):

> [Line 277:41](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/energyLineTest.py#L277): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 202:121](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/energyLineTest.py#L202): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (152 > 120 characters)
> [Line 119:121](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/energyLineTest.py#L119): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 100:71](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/energyLineTest.py#L100): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 100:69](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/energyLineTest.py#L100): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 86:69](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/energyLineTest.py#L86): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 54:1](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/energyLineTest.py#L54): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 51:121](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/energyLineTest.py#L51): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 120 characters)

* In the file [`avaframe/ana1Tests/simiSolTest.py`](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/simiSolTest.py):

> [Line 861:38](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/simiSolTest.py#L861): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 749:72](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/simiSolTest.py#L749): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 747:121](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/simiSolTest.py#L747): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 738:121](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/simiSolTest.py#L738): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 120 characters)
> [Line 722:121](https://github.com/avaframe/AvaFrame/blob/80cdaee83429fa23a9985a4e34e9eb7bc9c78564/avaframe/ana1Tests/simiSolTest.py#L722): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long  [...]

2022-03-11 09:00 UTC, matthiasto commented on avaframe/data/avaDamBreak/Inputs/damBreak_com1DFACfg.ini
> +xEnd = 220
take this for the analytical sol x axis

2022-03-11 09:03 UTC, matthiasto commented on avaframe/data/avaSimilaritySol/Inputs/simiSol_com1DFACfg.ini
check that it runs with no error

2022-03-11 09:14 UTC, matthiasto commented on avaframe/out3Plot/outAna1Plots.py
> +    pU.putAvaNameOnPlot(ax6, avalancheDir)
check x axis

2022-03-11 09:14 UTC, matthiasto commented on avaframe/out3Plot/outAna1Plots.py
> +    ax3.set_xlim([-200, 200])
use ini parameters

2022-03-11 09:20 UTC, matthiasto commented on avaframe/out3Plot/outAna1Plots.py
>  def plotPresentation(simDF, outDirTest, cfgSimi, xField, yField, coloredBy, sizedBy, logScale=False, fit=False):
add more info about how to use the function

2022-03-11 09:23 UTC, matthiasto commented on avaframe/out3Plot/outAna1Plots.py
>  def plotErrorConvergence(simDF, outDirTest, cfgSimi, xField, yField, coloredBy, sizedBy, logScale=False, fit=False):
try to merge with plot presentation

2022-03-11 09:29 UTC, matthiasto commented on avaframe/tests/data/testSimiSol/simiSol_com1DFACfg.ini
clean

2022-03-11 10:25 UTC, awirb requested changes

2022-03-15 08:34 UTC, awirb commented
in the summary figure DamBreak
* remove gray dashed lines in top and bottom row, only show area for error computation domain 
* add label of error computation domain in map view plot 
* would it be enough to say error domain? 
* be sure that lines are not capped in top row plots 
* rename init to initial in top row legend 
* maybe add option to list parameter values in list next to plots (from ini file) 
* be consistent with capital letters at start of a line 

in the summary figure simiSol
* maybe add option to list parameter values in list next to plots (from ini file) 
* be consistent with capital letters at start of a line 
* either remove legend on one of top level panels or remove Field..

2022-03-15 08:44 UTC, awirb requested changes

2022-03-15 08:44 UTC, awirb commented on avaframe/com1DFA/com1DFA.py
>              field is found - optional
add info on atol

2022-03-15 08:44 UTC, awirb commented on avaframe/com1DFA/com1DFA.py
>              field is found - optional
add info on Returns

2022-03-15 08:44 UTC, awirb commented on avaframe/data/avaDamBreak/Inputs/damBreak_com1DFACfg.ini
> +# ploting flags
maybe make this more obvious 
#++++Plotting parameters++++++

2022-03-15 08:44 UTC, awirb commented on avaframe/data/avaSimilaritySol/Inputs/simiSol_com1DFACfg.ini
>  ascendingOrder = False
general comment ini file: clean those parameters that are not different compared to default

2022-03-15 08:44 UTC, awirb commented on avaframe/data/avaSimilaritySol/Inputs/simiSol_com1DFACfg.ini
> +# ploting flags
same as for dambreak #++++++Plotting parameters++++++

2022-03-15 08:44 UTC, awirb commented on avaframe/runScripts/runAnalyzeDamBreak.py
> +#     simDF = pd.read_pickle(pathToResults)
make a comment when to use this?

2022-03-15 08:44 UTC, awirb commented on avaframe/runScripts/runAnalyzeDamBreak.py
> +# make convergence plot (if you add the fiting lines, make sure only the coloredBy and sizedBy parameters are varied)
maybe add what is different compared to line 53

2022-03-15 08:44 UTC, awirb commented on avaframe/runScripts/runDamBreak.py
> +for sphKernelRadius in [5, 3]:
hmm.. this is varied here as you want to vary it simultaneously with the meshcellsize right? maybe we could make a function of this and then call it?

2022-03-16 09:45 UTC, fso42 requested changes
- I like the animations, BUT I don't think they should autoplay. -> check if sphinx/rtd have a solution for that
- Address the pep8 issues

2022-03-16 09:45 UTC, fso42 commented on avaframe/ana1Tests/damBreak.py
> +                             solDam['uAna'], indTime, limits['maxFV'], pU.cfgPlotUtils['nameFV'] + ' in slope directrion', pU.cfgPlotUtils['unitFV'])
```suggestion
                             solDam['uAna'], indTime, limits['maxFV'], pU.cfgPlotUtils['nameFV'] + ' in slope directrion', 
                             pU.cfgPlotUtils['unitFV'])
```

2022-03-16 09:45 UTC, fso42 commented on avaframe/ana1Tests/damBreak.py
> +    deltaDeg = cfgC['DAMBREAK'].getfloat('delta')       # acceleration due to gravity [ms-2]
slople angle instead of acceleration...
bed friction... instead of acceleration...

2022-03-16 09:45 UTC, fso42 commented on avaframe/ana1Tests/damBreak.py
> +    hR = cfgC['GENERAL'].getfloat('relTh')        # initial height [m] in Riemann problem in state 1 (x<0), hR (x>0)=0
Unnecessary, use `hL` instead

2022-03-16 09:45 UTC, fso42 commented on avaframe/ana1Tests/damBreak.py
> +        # particlesList, timeStepInfo = particleTools.readPartFromPickle(avalancheDir, simName=simHash, flagAvaDir=True, comModule='com1DFA')
remove?

2022-03-16 09:45 UTC, fso42 commented on avaframe/com1DFA/com1DFA.py
> +def readFields(inDir, resType, simName='', flagAvaDir=True, comModule='com1DFA', timeStep='', atol=1.e-6):
Add `atol` to the docstring

2022-03-16 09:45 UTC, fso42 commented on avaframe/out3Plot/outAna1Plots.py
> +    """ Plot sumary figure of the damnreak test
Dambreak or SimiSol?

2022-03-16 09:45 UTC, fso42 commented on avaframe/out3Plot/outAna1Plots.py
> +    CB = pU.addColorBar(cs1, ax1, ticks, pU.cfgPlotUtils['unitFD'], title=pU.cfgPlotUtils['nameFD'], extend='both', pad=0.05, tickLabelsList='')
```suggestion
    CB = pU.addColorBar(cs1, ax1, ticks, pU.cfgPlotUtils['unitFD'], title=pU.cfgPlotUtils['nameFD'], 
    extend='both', pad=0.05, tickLabelsList='')
```

2022-03-16 09:45 UTC, fso42 commented on docs/moduleAna1Tests.rst
> +This norm will give an overall measure of the deviations. It is then useful to
```suggestion
This norm will give an overall measure of the deviations. It is  useful to
```

2022-03-16 09:45 UTC, fso42 commented on docs/moduleAna1Tests.rst
> +The Dambreak test compares the results of the DFA simulation to the analytical solution of the "dam break" problem.
```suggestion
The Dambreak test compares the results of  DFA simulations to the analytical solution of the "dam break" problem.
```

2022-03-16 09:45 UTC, fso42 commented on docs/moduleAna1Tests.rst
> +It is therefore a very useful test case for validating simulation results coming from the dense flow avalanche computation module.
```suggestion
It is a useful test case for validating simulation results coming from the dense flow avalanche computation module.
```

2022-03-16 09:45 UTC, fso42 commented on docs/moduleAna1Tests.rst
> +This semi-analytic solution can be derived under very strict conditions and making one major assumption on the shape of the solution.
Which is the `major assumption`?

2022-03-16 09:45 UTC, fso42 commented on docs/moduleAna1Tests.rst
> +into an ODE using a similarity analysis method. Solving the ODE still requires a numerical integration but this last one is way
```suggestion
into an ODE using a similarity analysis method. Solving the ODE still requires a numerical integration but this last one is
```

2022-03-16 10:15 UTC, fso42 approved these changes

2022-03-16 10:38 UTC, awirb requested changes
maybe stick to computational module instead of also using computation module

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +:math:`f_{ref}` the reference solutions defined on an interval :math:`\Omega`.
the reference solution

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +the reference solution:
It is useful to normalize the norm of the deviation either by dividing with the norm of the reference solution: ... like this?

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +In the case of a depth integrated model as derived by Savage and Hutter, an analytical solution exists.
add citation for the Savage and Hutter reference

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +In the case of a depth integrated model as derived by Savage and Hutter, an analytical solution exists.
maybe with an (e.g. ..)

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +The functions computing the analytical solution and comparing it to the simulation results are to be
suggestion: can be found?

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +located in :py:mod:`out3Plot.outAna1Plots`. The input data for this example can be found in ``data/avaDamBreak``.
suggestion: The input data for this test case?

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +This test produces a summary figure combining a comparison between the analytic and simulation
analytical- and or analytic solution and simulation result?

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +result (cross cut along the flow direction) as well as a bird view and an error measure plot as
map view?

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +as shown in the following figure.
animated figure?

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +          Time evolution of the dam thickness, velocity and momentum
flow instead of dam

2022-03-16 10:38 UTC, awirb commented on docs/moduleAna1Tests.rst
> +The required input files are located in ``data/avaDamBreak``, where the model configuration file can
where also the

2022-03-16 12:17 UTC, awirb approved these changes

2022-03-16 13:03 UTC, merged