Speed fields
avaframe/AvaFrame pull request #728
Opened 2022-06-24 09:01 UTC by matthiasto

fix #694 fix #455

2022-06-24 09:01 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/e380c4e01eedf4ef5510b8a472bbff946585a4e4/avaframe/com1DFA/com1DFA.py):

> [Line 182:121](https://github.com/avaframe/AvaFrame/blob/e380c4e01eedf4ef5510b8a472bbff946585a4e4/avaframe/com1DFA/com1DFA.py#L182): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (140 > 120 characters)



Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2022-06-27 13:53 UTC, awirb requested changes

2022-06-27 13:53 UTC, awirb commented on avaframe/com1DFA/DFAfunctionsCython.pyx
> +  """Compute pressure"""
just for completeness, add docstring

2022-06-29 06:33 UTC, matthiasto commented on avaframe/com1DFA/com1DFA.py
>      fields = {}
I mean the function itself is called like this but I can add a comment

2022-06-29 06:40 UTC, matthiasto commented on avaframe/com1DFA/com1DFA.py
> +        fields['computeTA'] = False
What do you mean? should I do one for pta and a different flag for TA?

2022-06-29 07:02 UTC, fso42 requested changes

2022-06-29 07:02 UTC, fso42 commented on avaframe/com1DFA/com1DFA.py
> +                resField = resField * 0.001
Add a quick comment:
```
# convert from Pa to kPa
# convert from J to kJ
```

2022-06-30 11:47 UTC, awirb requested changes

2022-06-30 11:47 UTC, awirb commented on avaframe/com1DFA/com1DFA.py
> +        fields['computeTA'] = False
still no log.info('Computing travel angle')

2022-07-01 05:51 UTC, matthiasto commented on avaframe/out3Plot/plotUtils.py
> +             'pke': cmapEnergy}
there is no KE field, I only keep track of the peak value. The KE can be computed from FM and FV

2022-07-01 05:52 UTC, matthiasto commented on avaframe/com1DFA/com1DFA.py
> +        fields['computeTA'] = False
It is in the if part, not in the else

2022-07-01 07:19 UTC, awirb approved these changes

2022-07-04 08:20 UTC, merged