Multiple cfgs
avaframe/AvaFrame pull request #739
Opened 2022-07-06 14:17 UTC by awirb

if in a new function different modules are used - in the ini file for this function add a section called modName_override for each module that is called - configurations for these modules will be created using the (local if defaultConfig=False) default configuration and overriding the parameters from the modName_override section, in the end a function_settings.ini is saved to the outputs folder of the function where all the other parameters (which were not part of the override parameters are added in the override sections for easy reproduction)

2022-07-06 14:17 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/com3Hybrid/com3Hybrid.py`](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/com3Hybrid/com3Hybrid.py):

> [Line 130:121](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/com3Hybrid/com3Hybrid.py#L130): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (131 > 120 characters)
> [Line 102:121](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/com3Hybrid/com3Hybrid.py#L102): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (137 > 120 characters)
> [Line 84:121](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/com3Hybrid/com3Hybrid.py#L84): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 79:27](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/com3Hybrid/com3Hybrid.py#L79): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 54:121](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/com3Hybrid/com3Hybrid.py#L54): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (136 > 120 characters)

* In the file [`avaframe/in3Utils/cfgUtils.py`](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/in3Utils/cfgUtils.py):

> [Line 889:41](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/in3Utils/cfgUtils.py#L889): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 889:41](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/in3Utils/cfgUtils.py#L889): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 886:41](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/in3Utils/cfgUtils.py#L886): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 886:41](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/in3Utils/cfgUtils.py#L886): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 589:50](https://github.com/avaframe/AvaFrame/blob/afa3305d527ad610ed91bbebc12e4df4b3898980/avaframe/in3Utils/cfgUtils.py#L589): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2022-07-07 09:02 UTC, matthiasto requested changes

2022-07-07 09:02 UTC, matthiasto commented on avaframe/com3Hybrid/com3Hybrid.py
> +    hybridModelDFACfgFile = cfgUtils.writeCfgFile(avalancheDir, com1DFA, hybridModelDFACfg, fileName='com1DFA_settings', filePath=oPath)
why write this one and not also the AB and pathGeneration cfgs to file?

2022-07-07 10:41 UTC, awirb commented on avaframe/com3Hybrid/com3Hybrid.py
> +    hybridModelDFACfg = cfgUtils.getModuleConfig(com1DFA, fileOverride='', modInfo=False, toPrint=False,
what is your suggestion? I think it is actually pretty accurate the one thing is a file path that you have to provide the other is configparser object that has the override parameters in it..

2022-07-07 10:42 UTC, awirb commented on avaframe/com3Hybrid/com3Hybrid.py
> +        hybridModelPathCfg= cfgUtils.getModuleConfig(DFAPath, fileOverride='', modInfo=False, toPrint=False,
this is a good point!

2022-07-07 14:56 UTC, awirb commented
newly opened in PR #740

2022-07-07 14:56 UTC, closed without merging