Bugfixes in rangeTimePlots
avaframe/AvaFrame pull request #746
Opened 2022-07-28 13:52 UTC by snowtechblog

Hi Avaframe Team,

Thank you for the great simulation tool, I am really impressed how easy to use the tool is as soon one got a little starting help (thanks @matthiasto).

I had a look at the rangeTimePlots for the thalweg-time-diagrams (thanks @awirb for the great work), and fixed some bugs. Namely:
- the small velocity legend did not react to zoom/pan events of the figure, e.g. as soon as one programmatically changes the xlim or ylim of the plot, the legend was wrong.
- the max of the front velocity suffered some inconsistencies, thus, I tried to find a way how to neglect obviously (to large) velocities. For example, I found one case where the were 400m/s in the first second inside the release area... The first commit 3e516ad is overwritten from the last commit 4f5b9c8, however, the way the max front velocity was calculated before is still in the code and can be activated with the flag `old_algo=True` in `ana5Utils.distanceTimeAnalysis.approachVelocity`

Other small changes include a found double import, explicit setting of mpl backend 'agg' in some debugPlots function, and some PyCharm files were not excluded in the gitignore file.

Here 2 plots that show the correction of the legend, with the following steps
- make range-time-plot with legend filling the full axes
- zoom to 0-100s and -1000m-0m (from beta point)
- now: diagonal equates to 10m/s

Not working zoom:
![thalwegTime_FV_e557d4d8f9_wrong_legend_after_zooming](https://user-images.githubusercontent.com/20665817/181520579-c922611c-da31-43c0-9428-7306b3c0d8b3.png)

Working zoom, result as expected:
![thalwegTime_FV_e557d4d8f9_correct_legend_after_zooming](https://user-images.githubusercontent.com/20665817/181520721-ec946ec4-a183-487f-a9d7-5b1ea608e9bf.png)

And here 2 plots that show the updated way to calculate the max front velocity:

Max velocity found at first timestep somewhere in release area:
![thalwegTime_FV_e557d4d8f9_old_algo_True](https://user-images.githubusercontent.com/20665817/181520876-242056e5-72f0-45b6-83ff-035e5c847cfb.png)

max velocity found in the steepest part of the flowing front:
![thalwegTime_FV_e557d4d8f9_correct_maxvel](https://user-images.githubusercontent.com/20665817/181521084-8aef7615-f118-4bfc-9adb-b19722d6566d.png)

Note: the small kink in the front at 30s and -1300m distance is also neglected. We should discuss how strong the max front algorithm should filter those kinks.

Cheers, Anselm

2022-07-28 13:52 UTC, pep8speaks commented
Hello @snowtechblog! Thanks for opening this PR. 

* In the file [`avaframe/ana5Utils/distanceTimeAnalysis.py`](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py):

> [Line 749:18](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L749): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 747:37](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L747): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 745:23](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L745): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 727:31](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L727): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 677:1](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L677): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 254:9](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L254): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 253:9](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L253): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 252:9](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L252): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 249:5](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L249): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 241:5](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L241): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 168:121](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/ana5Utils/distanceTimeAnalysis.py#L168): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)

* In the file [`avaframe/com1DFA/particleInitialisation.py`](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/com1DFA/particleInitialisation.py):

> [Line 24:1](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/com1DFA/particleInitialisation.py#L24): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`avaframe/out3Plot/outDebugPlots.py`](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDebugPlots.py):

> [Line 5:1](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDebugPlots.py#L5): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 4:1](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDebugPlots.py#L4): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

* In the file [`avaframe/out3Plot/outDistanceTimeAnalysis.py`](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py):

> [Line 534:1](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L534): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file
> [Line 490:14](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L490): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 485:70](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L485): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 483:23](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L483): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 480:23](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L480): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 477:21](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L477): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 476:70](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L476): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 474:18](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L474): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 456:19](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L456): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 436:25](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L436): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 433:31](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L433): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 386:121](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L386): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 386:117](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L386): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 385:121](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L385): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 385:117](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L385): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 384:121](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L384): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 384:117](https://github.com/avaframe/AvaFrame/blob/4f5b9c8516bf480e69da9f98eac4b94d6f49a522/avaframe/out3Plot/outDistanceTimeAnalysis.py#L384): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Lin [...]

2022-08-08 07:57 UTC, matthiasto requested changes

2022-08-08 07:57 UTC, matthiasto commented on avaframe/ana5Utils/distanceTimeAnalysis.py
> +        timeListSorted_unique = timeListSorted_small[unique_idx]
Why do you need to remove these values?

2022-08-13 08:43 UTC, awirb commented on avaframe/ana5Utils/distanceTimeAnalysisCfg.ini
> +maxOrMean = max
this is only applied for the mean or max values of the TT diagram not the range time with radar field of view - so either this should be moved to the tt section of the configuration settings or also implemented for the range time diagram function: extractFrontAndMeanValuesRadar

2022-08-17 12:07 UTC, fso42 requested changes
Hi @snowtechblog, thanks for your contribution; it is much appreciated!
Two general points:
- I'm not sure whether I am missing something, but the first two plots in your comment are the same, right?
- We have the coding style of using camelCase for variable naming (and no underscores). I now put this up in the notes to developers in the documentation; see https://docs.avaframe.org/en/latest/develop.html. Since this wasn't up at the time of your contribution, if you want, I can change the source files and send them to you so you can commit them and get the correct attribution.

2022-08-17 12:07 UTC, fso42 commented on avaframe/out3Plot/outDistanceTimeAnalysis.py
> +def rangeTimeVelocityLegend(ax, maxVel, width=0.25, height=0.25, lw=0.5, textsize=7):
see my general remark about variable naming within this function

2022-08-17 12:07 UTC, fso42 commented on avaframe/out3Plot/outDistanceTimeAnalysis.py
> +    '''
These do not match the actual function parameters, please update.

2022-08-17 12:07 UTC, fso42 commented on avaframe/out3Plot/outDistanceTimeAnalysis.py
> +def rangeTimeVelocityLegend_depreciated(timeSteps, rangeGates, ax, maxVel, width=0.25, height=0.25, lw=0.5, textsize=6):
I assume this is meant to be 'deprecated'? 
If so, then there's no point in keeping it, so just remove these functions

2022-08-17 12:07 UTC, fso42 commented on avaframe/out3Plot/outDistanceTimeAnalysis.py
> +
please add all input parameters here

2022-09-05 16:06 UTC, snowtechblog commented
>     * I'm not sure whether I am missing something, but the first two plots in your comment are the same, right?

No, they are actually different: See the velocity legend (velocity sun) values. In the first plot, the diagonal has still 6.3m/s value, but it must update to the new zoom ratio which gives then 10m/s as shown in the second plot

2022-10-17 11:53 UTC, awirb requested changes

2022-10-18 07:22 UTC, fso42 approved these changes

2022-10-18 11:18 UTC, merged