Add dam com1 dfa
avaframe/AvaFrame pull request #756
Opened 2022-08-26 07:21 UTC by matthiasto

Split the cython files (this required to create some .pxd files)
Add the dam tool

To test it, avaParabola, avaBowl and avaKot have some dam Input data.
Activate the dam in the com1DFA ini file and run.

To compare to com1DFAOrig, choose the correct line (the one corresponding to the parabola, bowl or kot) in the createProject.cint
Run com1DFAOrig, then run com1DFA (using the same particles) and finally run the ana3AIMECComp

The documentation is on it's way.

2022-08-26 07:22 UTC, pep8speaks commented
Hello @matthiasto! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFA/com1DFA.py):

> [Line 185:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFA/com1DFA.py#L185): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)



* In the file [`avaframe/com1DFA/particleTools.py`](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFA/particleTools.py):

> [Line 552:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFA/particleTools.py#L552): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 150:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFA/particleTools.py#L150): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 37:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFA/particleTools.py#L37): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)

* In the file [`avaframe/com1DFAOrig/com1DFAOrig.py`](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py):

> [Line 462:5](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L462): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 448:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L448): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (166 > 120 characters)
> [Line 436:9](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L436): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 435:9](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L435): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 393:29](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L393): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 390:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L390): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 388:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L388): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (175 > 120 characters)
> [Line 385:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L385): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (174 > 120 characters)
> [Line 337:33](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L337): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 332:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L332): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (172 > 120 characters)
> [Line 318:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L318): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (132 > 120 characters)
> [Line 318:94](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L318): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> [Line 309:21](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L309): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 308:21](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L308): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 159:42](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/com1DFAOrig/com1DFAOrig.py#L159): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','

* In the file [`avaframe/in1Data/getInput.py`](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/in1Data/getInput.py):

> [Line 350:50](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/in1Data/getInput.py#L350): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 346:37](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/in1Data/getInput.py#L346): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 328:34](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/in1Data/getInput.py#L328): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 143:16](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/in1Data/getInput.py#L143): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is None:'
> [Line 139:16](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/in1Data/getInput.py#L139): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is None:'
> [Line 114:15](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/in1Data/getInput.py#L114): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 73:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/in1Data/getInput.py#L73): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)



* In the file [`avaframe/in3Utils/geoTrans.py`](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/in3Utils/geoTrans.py):

> [Line 1028:9](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/in3Utils/geoTrans.py#L1028): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line





* In the file [`avaframe/tests/test_DFAToolsCython.py`](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/tests/test_DFAToolsCython.py):

> [Line 266:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/tests/test_DFAToolsCython.py#L266): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (170 > 120 characters)
> [Line 243:121](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/tests/test_DFAToolsCython.py#L243): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (158 > 120 characters)

* In the file [`avaframe/tests/test_DFAfunctionsCython.py`](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/tests/test_DFAfunctionsCython.py):

> [Line 339:33](https://github.com/avaframe/AvaFrame/blob/da6aeab9f782d29234781d0702d836cc87016c64/avaframe/tests/test_DFAfunctionsCython.py#L339): [E712](https: [...]

2022-09-08 13:22 UTC, fso42 commented
'test_damCom1DFA.py' fails as the *WallLines functions expect wallLineDict['fileName'] . But as far as I can see this is only for log.infos?

2022-09-19 07:10 UTC, fso42 requested changes
General remark: any deeper reason why you use an indent of 2 (instead of our normal 4) spaces for the cython files?

2022-09-19 07:10 UTC, fso42 commented on avaframe/com1DFA/DFAfunctionsCython.pyx
> +
remove this?

2022-09-19 07:10 UTC, fso42 commented on avaframe/com1DFA/DFAfunctionsCython.pyx
> +      inter, xNew, yNew, zNew, uxNew, uyNew, uzNew, txWall, tyWall, tzWall, dEm = damCom1DFA.getWallInteraction(x, y, z,
plese add a pytest for this part (at least checking if it runs...)

2022-09-19 07:10 UTC, fso42 commented on avaframe/com1DFA/com1DFA.py
> +            damFile = inputSimFiles['damFile']
Please a a pytest to see if it runs

2022-09-19 07:10 UTC, fso42 commented on avaframe/com1DFA/particleTools.py
> +    # z = particles['z']
just remove these?

2022-09-19 07:10 UTC, fso42 commented on avaframe/in3Utils/geoTrans.py
> +    based on https://stackoverflow.com/a/35808540/15887086
Please expand the docstring

2022-09-20 11:24 UTC, awirb requested changes

2022-09-20 11:24 UTC, awirb commented on avaframe/in3Utils/geoTrans.py
> +def getCellsAlongLine(header, lineDict, addBuffer=True):
general question, is it an option to make a buffered line and look for the affected cells, maybe shapely offers tools for this, similar to the create ReleaseBuffer function..

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +This is done using a haddock method based on particles bouncing on a dam wall.
```suggestion
This is done using an ad-hoc method based on particles bouncing on a dam wall.
```

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +This is done using a haddock method based on particles bouncing on a dam wall.
maybe bouncing back or being reflected/deflected by a dam wall?

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +This is done using a haddock method based on particles bouncing on a dam wall.
and maybe based on the idea of particles ---

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +  * crown line as shape file (use the line type and enable the enable the "additional dimentions" option in order
```suggestion
  * crown line as shape file (use the line type and enable the "additional dimensions" option in order
```

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +    to specify the z coordinate). The z coordinate corresponds to the absolute height. The dam is then located on the
```suggestion
    to specify the z coordinate). The z coordinate corresponds to the absolute height (terrain elevation plus dam height). The dam is then located on the
```

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +    left side of the dam. The dam shape files lives in the ``avaDir/Inputs/DAM/`` directory.
```suggestion
    left side of the dam. The dam shape files live in the ``avaDir/Inputs/DAM/`` directory. 
```

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +    left side of the dam. The dam shape files lives in the ``avaDir/Inputs/DAM/`` directory.
only one allowed? maybe add this info

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +is intersection between the dam wall and the topography (:math:`\mathbf{x_\text{foot}}`).
```suggestion
is the intersection between the dam wall and the topography (:math:`\mathbf{x_\text{foot}}`).
```

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +The normal and tangent vectors to the dam wall is readjusted accordingly.
```suggestion
The normal and tangent vectors to the dam wall are readjusted accordingly.
```

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +          Side view of the dam (cut view). :math:`\mathbf{x_\text{crown}}` describe the crown
```suggestion
          Side view of the dam (cut view). :math:`\mathbf{x_\text{crown}}` describes the crown
```

2022-09-20 11:24 UTC, awirb commented on docs/damToolCom1DFA.rst
> +          (filling of the dam)
(filling of the dam, n_w _filled).

2022-09-21 06:49 UTC, fso42 commented on avaframe/out3Plot/outDebugPlots.py
> +# matplotlib.use('agg')
Ah no, please either remove or leave it commented. See issues #745 and #573

2022-11-10 15:28 UTC, fso42 requested changes
General remark: the pyx files have a ident setting of 2, whereas the rest of our code has 4. Please check whether you can easily reindent with your editor. Otherwise let me know and I'll try... (But I'd prefer you showing up as the contributor for those lines :-) )

2022-11-10 15:28 UTC, fso42 commented on avaframe/in3Utils/geoTrans.py
> +        which key in the Points dict should be updated with the interpolated data?
mh, not sure whether what/where are the best names. from/to ? source/target? sourceKey/targetKey?

2022-11-17 21:00 UTC, merged