add contour plot to aimec
avaframe/AvaFrame pull request #778
Opened 2022-11-03 11:45 UTC by awirb

2022-11-08 07:16 UTC, matthiasto commented on avaframe/out3Plot/outAIMEC.py
> +    L, S = np.meshgrid(l, s)
do not use the same letters but gridL gridS for example

2022-11-08 07:19 UTC, fso42 requested changes

2022-11-08 07:19 UTC, fso42 commented on avaframe/ana3AIMEC/ana3AIMEC.py
> +        for thresholdValue
Maybe add what was added to the contourDict? VS on the input side

2022-11-08 07:19 UTC, fso42 commented on avaframe/ana4Stats/probAna.py
> +                contourDict[fileName.stem] = {'x': x, 'y': y}
Did you check whether this slows the function down? sometimes contour generation can take quite some time...

2022-11-09 18:59 UTC, fso42 commented on avaframe/ana4Stats/probAna.py
> +                contourDict[fileName.stem] = {'x': x, 'y': y}
I tried. since it is only on contour per sim, it is not slowing it down

2022-11-10 10:21 UTC, fso42 approved these changes

2022-11-10 10:21 UTC, merged