started the glossary over - did not connect all terms and references yet
avaframe/AvaFrame pull request #830
Opened 2023-03-08 18:28 UTC by jtfisch

I re-started the glossary to be applicable to all different modules of avaframe, particularly the coming AMA and flowpy parts. Not all 'terms' and references are linked yet.

2023-03-09 09:16 UTC, fso42 approved these changes

2023-03-13 09:37 UTC, awirb requested changes

2023-03-13 09:37 UTC, awirb commented on docs/glossary.rst
> +        of the flow.
```suggestion
        where the maximum over the whole flow or computational duration, I.e.,
        their peak values are the most used results. The flow variables are used to derive other variables such as impact pressure or kinetic energy
        of the flow.
```

2023-03-13 09:37 UTC, awirb commented on docs/glossary.rst
> +        to the :term:`thalweg`.
```suggestion
        to the :term:`thalweg`. Or projecting a 3D travel length (xyz) to a 2D travel length measured only along xy.
```

2023-03-13 09:37 UTC, awirb commented on docs/glossary.rst
> +        Runout lengths and angles are intricately linked to the :term:`alpha` point, itilizing the
```suggestion
        Runout lengths and angles are intricately linked to the :term:`alpha` point, utilizing the
```

2023-03-13 09:37 UTC, awirb commented on docs/glossary.rst
> +        corresponding angle, measured between the line connecting the current
```suggestion
        corresponding travel angle, measured between the line connecting the current
```

2023-03-15 14:52 UTC, merged