compute min, mean values for result fields in aimec with masking 0 va…
avaframe/AvaFrame pull request #923
Opened 2023-10-04 14:03 UTC by awirb

…lues

2023-10-04 14:03 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/ana3AIMEC/ana3AIMEC.py`](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py):

> [Line 499:5](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L499): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 453:9](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L453): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 444:13](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L444): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 442:64](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L442): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 442:38](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L442): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 439:62](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L439): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 438:62](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L438): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 355:121](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L355): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 348:121](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L348): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 165:13](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L165): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 150:121](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L150): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 145:121](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L145): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 64:121](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L64): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 59:121](https://github.com/avaframe/AvaFrame/blob/bf9eda2b00c605867753dd5a47487a307e2d6683/avaframe/ana3AIMEC/ana3AIMEC.py#L59): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2023-10-05 08:00 UTC, fso42 requested changes

2023-10-05 08:06 UTC, awirb commented on avaframe/ana3AIMEC/ana3AIMEC.py
> +            maskedRaster = np.where(rasterData['rasterData'] == 0., np.nan, rasterData['rasterData'])
hardcoded or read from an ini file?

2023-10-05 19:15 UTC, fso42 approved these changes

2023-10-05 19:17 UTC, merged