Add com6 rock avalanche [com6]
avaframe/AvaFrame pull request #939
Opened 2023-11-16 16:03 UTC by fso42

This adds a com6RockAvalanche similar to com5, i.e. an override setup for com1DFA

2023-11-23 12:46 UTC, pep8speaks commented
Hello @fso42! Thanks for updating this PR. 







* In the file [`avaframe/tests/test_com6RockAvalanche.py`](https://github.com/avaframe/AvaFrame/blob/bb793c1d80e3c61a060b698ba6f3a78e224d61ce/avaframe/tests/test_com6RockAvalanche.py):

> [Line 51:1](https://github.com/avaframe/AvaFrame/blob/bb793c1d80e3c61a060b698ba6f3a78e224d61ce/avaframe/tests/test_com6RockAvalanche.py#L51): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file
> [Line 44:5](https://github.com/avaframe/AvaFrame/blob/bb793c1d80e3c61a060b698ba6f3a78e224d61ce/avaframe/tests/test_com6RockAvalanche.py#L44): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 21:1](https://github.com/avaframe/AvaFrame/blob/bb793c1d80e3c61a060b698ba6f3a78e224d61ce/avaframe/tests/test_com6RockAvalanche.py#L21): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2023-11-28 12:14 UTC, awirb requested changes

2023-11-28 19:00 UTC, fso42 commented on docs/connector.rst
> +      Runs rock avalanche simulations via module com1DFA. For more info see com6RockAvalanche section in the
It is in the experimental section, so I don't want to add experimental to all these functions, as I think this is highly redundant...

2023-11-29 12:00 UTC, fso42 commented
Standardtests ok (basically ident)

2023-11-30 13:41 UTC, merged