com4FlowPy bug-fixes/added functionality
avaframe/AvaFrame pull request #974
Opened 2024-05-15 16:05 UTC by ahuber-bfw

## com4FlowPy update:
* minor bug fixes
*  added functionality:
    * Forest-Friction and Detrainment functionality (old Flow-Py Repo ```foreste_detrainment``` branch)
    * Functionality for custom-directory definition (input-files, output folder)
* started to expose most important model parameters in .ini file

* updated splitting of release cells and multiprocessing
* added (simple) memory management

* started re-structuring of the code and documentation

__introduces additional requirement psutil !__ (memory management)

2024-05-15 16:06 UTC, pep8speaks commented
Hello @ahuber-bfw! Thanks for opening this PR. 

* In the file [`avaframe/com4FlowPy/com4FlowPy.py`](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py):

> [Line 406:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L406): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 405:53](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L405): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 402:38](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L402): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 402:18](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L402): [E211](https://duckduckgo.com/?q=pep8%20E211) whitespace before '('
> [Line 396:71](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L396): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 394:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L394): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 392:30](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L392): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 391:44](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L391): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 386:22](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L386): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 382:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L382): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 374:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L374): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 367:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L367): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 364:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L364): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 346:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L346): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 337:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L337): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 333:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L333): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 331:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L331): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 330:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L330): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 329:121](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L329): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 323:94](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L323): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 323:5](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L323): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 322:5](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L322): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 321:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L321): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 311:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L311): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 307:10](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L307): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 306:10](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L306): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 303:9](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L303): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 302:12](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L302): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 293:1](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L293): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 287:49](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L287): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 287:44](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L287): [E228](https://duckduckgo.com/?q=pep8%20E228) missing whitespace around modulo operator
> [Line 285:49](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L285): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 285:44](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L285): [E228](https://duckduckgo.com/?q=pep8%20E228) missing whitespace around modulo operator
> [Line 284:10](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L284): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 278:17](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L278): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 272:19](https://github.com/avaframe/AvaFrame/blob/f5f950490321befbd81cc286379f366f38632096/avaframe/com4FlowPy/com4FlowPy.py#L272): [E231](https:/ [...]

2024-05-15 19:02 UTC, fso42 requested changes
Thanks for your PR!

As a note, I did not do a functional test of com4 but rather only an "administrative" test. I left the functional testing to @PaulaSp3.

You don't need to change this now, but when you touch a function in the future, you should change the docstring style to the numpy style (see the link I sent; I'll include this in our docs, see #975 ). 

About the formatting of the code: Maybe we should discuss whether to apply the black formatter at this stage since everything has changed anyway. We (loosely) use the black formatter since it makes it easier. However, on the first application, all lines will be attributed to the person submitting the commit, which, in this case, does not matter that much, I would say.

- [x] add the psutil requirement to the documentation page -> now included in requirements
- [x] address the undefined variables that show up in the linting

2024-05-17 07:46 UTC, fso42 commented
Mh, If you prefer @ahuber-bfw, I think we could include psutil in the general setup. Then the documentation update is not needed...

2024-05-21 13:55 UTC, ahuber-bfw commented on avaframe/com4FlowPy/com4FlowPy.py
> +    modelParameters["alpha"]          = float(cfgSetup["alpha"])
- [x] thanks, I updated the lines in ```com4FlowPy.py``` to use the ```cfgSetup``` functions accordingly.
- [x] I also addressed the undefined variables that popped up in the linting
- [ ] I did not touch the formatting issue yet, but had a look at the ```black``` formatter you suggested - do you have a config file for ```black``` that can be used?

2024-05-21 17:54 UTC, fso42 commented on avaframe/com4FlowPy/com4FlowPy.py
> +    modelParameters["alpha"]          = float(cfgSetup["alpha"])
@ black formatter: Let's discuss this in a quick call/meeting and whether it makes sense to apply it now. @config: Black is all about "sensible defaults" (see https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html -> Configuration via file), so we are using it in the default setup. The only difference is the line length, which is already set in AvaFrame's pyproject.toml and should be picked up by black.

2024-05-22 11:00 UTC, ahuber-bfw commented on avaframe/com4FlowPy/com4FlowPy.py
> +    modelParameters["alpha"]          = float(cfgSetup["alpha"])
@fso42 - @ black formatter
* i ran the black formatter on the com4FlowPy files and added some minor manual mods where I wasn't satisfied with the default outputs
* --> see commit:  74ec0dc1288340d572459403f344b3ce78a2c0cf

hope this solves most of the formatting related issues of the PR

2024-05-22 11:27 UTC, PaulaSp3 reviewed
Lines 182 should it not be release[release > 0] = 1 ? In case release areas are assigned to values between 0 and 1?

2024-05-22 11:37 UTC, ahuber-bfw commented on avaframe/com4FlowPy/flowClass.py
* no they are not strictly necessary 
* just added the internal-use variables for better readability of the two formulas
* (self.noFrictionEffectV * self.noFricitonEffectV) / (self._SQRT2 * 9.81) would work just the same ...

2024-05-22 11:42 UTC, ahuber-bfw commented on avaframe/com4FlowPy/flowClass.py
about the ```release[release>1] = 1``` --> ```release[release>0] = 1```:
* you're right, this seems to be more robust

2024-05-22 16:31 UTC, fso42 commented on avaframe/com4FlowPy/com4FlowPy.py
> +    modelParameters["alpha"]          = float(cfgSetup["alpha"])
Nice, the bare excepts are ok in my opinion.

2024-05-22 17:02 UTC, fso42 approved these changes

2024-05-23 09:25 UTC, PaulaSp3 approved these changes

2024-05-23 09:34 UTC, ahuber-bfw commented on avaframe/com4FlowPy/flowCore.py
Yes, that would probably make sense - we could then handle this in the flowClass.Cell() constructor (i.e. instead of checking if FSI and forestParames is not None we could check which keys are in the dictionary ...). We can address this as an idea for future improvement.

2024-05-23 19:20 UTC, fso42 commented
Standardtests ok (apart from known avaKot)

2024-05-23 19:21 UTC, merged