adjust extent of plots and add tesets
avaframe/AvaFrame pull request #982
Opened 2024-05-23 09:54 UTC by awirb

* extent for imshow plots - if provided in meters requires to take 0.5*cellsize into account as rasters are provided with llcellcenter as origin
* adjust constrainToData that if data reaches to raster margin - rowsMax and colsMax index is data.shape[0]-1 or data.shape[1]-1 as rowsMin:rowsMax+1, colsMin:colsMax+1 is used as index so that when rowsMax< data.shape[0] also the row of rowsMax index is added 
* add pytest
* add check if extent is in line with nrows, ncols of data array

2024-05-23 09:54 UTC, pep8speaks commented
Hello @awirb! Thanks for opening this PR. 

* In the file [`avaframe/ana4Stats/probAna.py`](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/ana4Stats/probAna.py):

> [Line 807:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/ana4Stats/probAna.py#L807): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 700:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/ana4Stats/probAna.py#L700): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)
> [Line 699:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/ana4Stats/probAna.py#L699): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (167 > 120 characters)
> [Line 635:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/ana4Stats/probAna.py#L635): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 470:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/ana4Stats/probAna.py#L470): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 406:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/ana4Stats/probAna.py#L406): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 120 characters)
> [Line 399:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/ana4Stats/probAna.py#L399): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 188:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/ana4Stats/probAna.py#L188): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)

* In the file [`avaframe/out1Peak/outPlotAllPeak.py`](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out1Peak/outPlotAllPeak.py):

> [Line 194:5](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out1Peak/outPlotAllPeak.py#L194): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 184:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out1Peak/outPlotAllPeak.py#L184): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 176:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out1Peak/outPlotAllPeak.py#L176): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 176:62](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out1Peak/outPlotAllPeak.py#L176): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 176:35](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out1Peak/outPlotAllPeak.py#L176): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 168:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out1Peak/outPlotAllPeak.py#L168): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 10:1](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out1Peak/outPlotAllPeak.py#L10): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

* In the file [`avaframe/out3Plot/outDistanceTimeAnalysis.py`](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/outDistanceTimeAnalysis.py):

> [Line 83:5](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/outDistanceTimeAnalysis.py#L83): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 60:42](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/outDistanceTimeAnalysis.py#L60): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

* In the file [`avaframe/out3Plot/outQuickPlot.py`](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/outQuickPlot.py):

> [Line 166:48](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/outQuickPlot.py#L166): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'

* In the file [`avaframe/out3Plot/plotUtils.py`](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py):

> [Line 970:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L970): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (138 > 120 characters)
> [Line 968:19](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L968): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 936:21](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L936): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 790:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L790): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 674:37](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L674): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 673:37](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L673): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 522:15](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L522): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 486:71](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L486): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 486:48](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L486): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 480:71](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L480): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 480:48](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L480): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'
> [Line 467:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/plotUtils.py#L467): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

* In the file [`avaframe/out3Plot/statsPlots.py`](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/statsPlots.py):

> [Line 626:121](https://github.com/avaframe/AvaFrame/blob/4aed24f55bedd32fa340a470120fad18f2e9fbc9/avaframe/out3Plot/statsPlots.py#L626): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)
> [Line 594:56](https://github.com/avafra [...]

2024-05-27 18:05 UTC, fso42 requested changes

2024-05-27 18:05 UTC, fso42 commented on avaframe/out3Plot/plotUtils.py
> +    extenctCellCorners: list
typo extenct....

2024-05-27 18:05 UTC, fso42 commented on avaframe/out3Plot/plotUtils.py
> +        extent corresponding to the cell corner coordinates (lowerleft corner, uperright corner)
lower left and upper right

2024-05-27 18:05 UTC, fso42 commented on avaframe/out3Plot/plotUtils.py
> +def createExtentMinMax(data, header, originLLCenter=True):
originLLCenter is missing in docstring

2024-05-27 18:05 UTC, fso42 commented on avaframe/out3Plot/statsPlots.py
> +            ls, CS = pU.addHillShadeContours(ax1, demConstrained, cellSize, extentCellCenters)
returns are not used, remove them (or replace with _)

2024-05-28 07:34 UTC, awirb commented on avaframe/out1Peak/outPlotAllPeak.py
> +    extentCellCenters, extentCellCorners, rowsMinPlot, rowsMaxPlot, colsMinPlot, colsMaxPlot = pU.createExtent(rowsMin, rowsMax, colsMin, colsMax, dataConstrained, raster['header'])
rowsMinPlot, colsMinPlot are returned by the function - so I kept them

2024-05-28 08:12 UTC, awirb commented on avaframe/out3Plot/outDistanceTimeAnalysis.py
> +    im1 = ax1.imshow(bmaskRange, extent=[x0-shiftCorner, x1-shiftCorner, y0-shiftCorner, y1-shiftCorner], origin="lower", aspect=nx / ny)
this was a bug - they are all the same extents - I adjusted this and added comments

2024-05-28 08:28 UTC, fso42 approved these changes

2024-05-28 08:28 UTC, fso42 commented on avaframe/out3Plot/plotUtils.py
> +    """constrain input raster dataset to where there is data plus buffer zone
constrainedData is not in the docstring

2024-05-28 11:51 UTC, fso42 commented
Standardtests ok, apart from know avaKot

2024-05-28 11:51 UTC, merged