[com1DFA]: Add options for computing resistance (especially dealing with hEff)
avaframe/AvaFrame pull request #993
Opened 2024-06-25 11:07 UTC by PaulaSp3

added options: 
1. (as before) hEff = min(h, h_res)
2. hEff = const and included in parameter cResH
3. add to option 1 a Coulomb-term 
4. add to option 2 a Coulomb-term 

the options are for experimental tests, we should remove those that are unnecessary.

2024-06-25 11:07 UTC, pep8speaks commented
Hello @PaulaSp3! Thanks for opening this PR. 

* In the file [`avaframe/com1DFA/com1DFA.py`](https://github.com/avaframe/AvaFrame/blob/1e420b47b531329d50e3e74bf691a26a2b2cc70a/avaframe/com1DFA/com1DFA.py):

> [Line 1713:50](https://github.com/avaframe/AvaFrame/blob/1e420b47b531329d50e3e74bf691a26a2b2cc70a/avaframe/com1DFA/com1DFA.py#L1713): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 1614:28](https://github.com/avaframe/AvaFrame/blob/1e420b47b531329d50e3e74bf691a26a2b2cc70a/avaframe/com1DFA/com1DFA.py#L1614): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1612:27](https://github.com/avaframe/AvaFrame/blob/1e420b47b531329d50e3e74bf691a26a2b2cc70a/avaframe/com1DFA/com1DFA.py#L1612): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 1610:121](https://github.com/avaframe/AvaFrame/blob/1e420b47b531329d50e3e74bf691a26a2b2cc70a/avaframe/com1DFA/com1DFA.py#L1610): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2024-07-01 08:07 UTC, fso42 commented on avaframe/com1DFA/com1DFA.py
> +    if ResModel in ["cRes", "cResCoulomb"]:
To avoid potential problems with typos, use .lower to compare (ie. if user writes cRescoulomb (lower c), it should work too)

2024-07-01 08:11 UTC, fso42 requested changes
Please look into the failing pytests

2024-08-13 17:07 UTC, fso42 approved these changes

2024-12-10 10:33 UTC, fso42 approved these changes

2024-12-10 11:53 UTC, awirb approved these changes

2024-12-19 13:47 UTC, fso42 approved these changes

2024-12-19 15:47 UTC, fso42 commented
Standardtests ok, apart from known (KOT and PFA)

2024-12-19 15:48 UTC, merged